export type GameDifficulty = "easy" | "mixed" | "hard";
export type GameCategory = "Object" | "Nature" | "Person" | "Action" | "World" | "Random";

export interface GameWord {
  word: string;
  category: GameCategory;
  difficulty: "easy" | "medium" | "hard";
}

export const GAME_CATEGORIES: GameCategory[] = [
  "Object", "Nature", "Person", "Action", "World", "Random",
];

export const CATEGORY_COLORS: Record<GameCategory, string> = {
  Object:  "#8C6239", // warm sienna
  Nature:  "#16A34A", // vibrant emerald green
  Person:  "#5A4565", // muted plum
  Action:  "#A67C1E", // bronze gold
  World:   "#4E5460", // slate navy
  Random:  "#6B4C7A", // deep violet
};

export const CATEGORY_ICONS: Record<GameCategory, string> = {
  Object:  "📦",
  Nature:  "🌿",
  Person:  "👤",
  Action:  "⚡",
  World:   "🌍",
  Random:  "🎲",
};

export const GAME_WORDS: GameWord[] = [
  // ─── OBJECT ───────────────────────────────────────────────────────────────
  // Easy
  { word: "Umbrella",        category: "Object", difficulty: "easy" },
  { word: "Stapler",         category: "Object", difficulty: "easy" },
  { word: "Toothbrush",      category: "Object", difficulty: "easy" },
  { word: "Mirror",          category: "Object", difficulty: "easy" },
  { word: "Keyboard",        category: "Object", difficulty: "easy" },
  { word: "Scissors",        category: "Object", difficulty: "easy" },
  { word: "Pillow",          category: "Object", difficulty: "easy" },
  { word: "Alarm Clock",     category: "Object", difficulty: "easy" },
  { word: "Wallet",          category: "Object", difficulty: "easy" },
  { word: "Remote Control",  category: "Object", difficulty: "easy" },
  { word: "Sunglasses",      category: "Object", difficulty: "easy" },
  { word: "Backpack",        category: "Object", difficulty: "easy" },
  { word: "Candle",          category: "Object", difficulty: "easy" },
  { word: "Headphones",      category: "Object", difficulty: "easy" },
  { word: "Calendar",        category: "Object", difficulty: "easy" },
  // Medium
  { word: "Periscope",       category: "Object", difficulty: "medium" },
  { word: "Compass",         category: "Object", difficulty: "medium" },
  { word: "Abacus",          category: "Object", difficulty: "medium" },
  { word: "Megaphone",       category: "Object", difficulty: "medium" },
  { word: "Microscope",      category: "Object", difficulty: "medium" },
  { word: "Telescope",       category: "Object", difficulty: "medium" },
  { word: "Hourglass",       category: "Object", difficulty: "medium" },
  { word: "Typewriter",      category: "Object", difficulty: "medium" },
  { word: "Metronome",       category: "Object", difficulty: "medium" },
  { word: "Sundial",         category: "Object", difficulty: "medium" },
  // Hard
  { word: "Oscilloscope",    category: "Object", difficulty: "hard" },
  { word: "Astrolabe",       category: "Object", difficulty: "hard" },
  { word: "Centrifuge",      category: "Object", difficulty: "hard" },
  { word: "Autoclave",       category: "Object", difficulty: "hard" },
  { word: "Tachometer",      category: "Object", difficulty: "hard" },

  // ─── NATURE ───────────────────────────────────────────────────────────────
  // Easy
  { word: "Penguin",         category: "Nature", difficulty: "easy" },
  { word: "Volcano",         category: "Nature", difficulty: "easy" },
  { word: "Daisy",           category: "Nature", difficulty: "easy" },
  { word: "Tornado",         category: "Nature", difficulty: "easy" },
  { word: "Dolphin",         category: "Nature", difficulty: "easy" },
  { word: "Cactus",          category: "Nature", difficulty: "easy" },
  { word: "Rainbow",         category: "Nature", difficulty: "easy" },
  { word: "Whale",           category: "Nature", difficulty: "easy" },
  { word: "Mushroom",        category: "Nature", difficulty: "easy" },
  { word: "Avalanche",       category: "Nature", difficulty: "easy" },
  { word: "Flamingo",        category: "Nature", difficulty: "easy" },
  { word: "Oak Tree",        category: "Nature", difficulty: "easy" },
  { word: "Thunderstorm",    category: "Nature", difficulty: "easy" },
  { word: "Starfish",        category: "Nature", difficulty: "easy" },
  { word: "Glacier",         category: "Nature", difficulty: "easy" },
  // Medium
  { word: "Pangolin",        category: "Nature", difficulty: "medium" },
  { word: "Bioluminescence", category: "Nature", difficulty: "medium" },
  { word: "Permafrost",      category: "Nature", difficulty: "medium" },
  { word: "Lichen",          category: "Nature", difficulty: "medium" },
  { word: "Mangrove",        category: "Nature", difficulty: "medium" },
  { word: "Platypus",        category: "Nature", difficulty: "medium" },
  { word: "Stalactite",      category: "Nature", difficulty: "medium" },
  { word: "Tundra",          category: "Nature", difficulty: "medium" },
  { word: "Maelstrom",       category: "Nature", difficulty: "medium" },
  { word: "Quartz",          category: "Nature", difficulty: "medium" },
  { word: "Fjord",           category: "Nature", difficulty: "medium" },
  { word: "Monsoon",         category: "Nature", difficulty: "medium" },
  { word: "Narwhal",         category: "Nature", difficulty: "medium" },
  { word: "Sinkhole",        category: "Nature", difficulty: "medium" },
  { word: "Supernova",       category: "Nature", difficulty: "medium" },
  // Hard
  { word: "Hadal Zone",      category: "Nature", difficulty: "hard" },
  { word: "Coriolis Effect", category: "Nature", difficulty: "hard" },
  { word: "Thermocline",     category: "Nature", difficulty: "hard" },
  { word: "Chemosynthesis",  category: "Nature", difficulty: "hard" },
  { word: "Albedo",          category: "Nature", difficulty: "hard" },

  // ─── PERSON ───────────────────────────────────────────────────────────────
  // Easy
  { word: "Albert Einstein", category: "Person", difficulty: "easy" },
  { word: "Cleopatra",       category: "Person", difficulty: "easy" },
  { word: "Shakespeare",     category: "Person", difficulty: "easy" },
  { word: "Nurse",           category: "Person", difficulty: "easy" },
  { word: "Firefighter",     category: "Person", difficulty: "easy" },
  { word: "Astronaut",       category: "Person", difficulty: "easy" },
  { word: "Chef",            category: "Person", difficulty: "easy" },
  { word: "Leonardo da Vinci",category: "Person", difficulty: "easy" },
  { word: "Nelson Mandela",  category: "Person", difficulty: "easy" },
  { word: "Queen Elizabeth", category: "Person", difficulty: "easy" },
  { word: "Bruce Lee",       category: "Person", difficulty: "easy" },
  { word: "Oprah Winfrey",   category: "Person", difficulty: "easy" },
  { word: "Elon Musk",       category: "Person", difficulty: "easy" },
  { word: "Surgeon",         category: "Person", difficulty: "easy" },
  { word: "Architect",       category: "Person", difficulty: "easy" },
  // Medium
  { word: "Nikola Tesla",    category: "Person", difficulty: "medium" },
  { word: "Marie Curie",     category: "Person", difficulty: "medium" },
  { word: "Karl Marx",       category: "Person", difficulty: "medium" },
  { word: "Sigmund Freud",   category: "Person", difficulty: "medium" },
  { word: "Galileo Galilei", category: "Person", difficulty: "medium" },
  { word: "Epidemiologist",  category: "Person", difficulty: "medium" },
  { word: "Confucius",       category: "Person", difficulty: "medium" },
  { word: "Machiavelli",     category: "Person", difficulty: "medium" },
  { word: "Anthropologist",  category: "Person", difficulty: "medium" },
  { word: "Socrates",        category: "Person", difficulty: "medium" },
  // Hard
  { word: "Maimonides",      category: "Person", difficulty: "hard" },
  { word: "Averroes",        category: "Person", difficulty: "hard" },
  { word: "Hypatia",         category: "Person", difficulty: "hard" },
  { word: "Ada Lovelace",    category: "Person", difficulty: "hard" },
  { word: "Ibn Battuta",     category: "Person", difficulty: "hard" },

  // ─── ACTION ───────────────────────────────────────────────────────────────
  // Easy
  { word: "Swimming",        category: "Action", difficulty: "easy" },
  { word: "Whispering",      category: "Action", difficulty: "easy" },
  { word: "Juggling",        category: "Action", difficulty: "easy" },
  { word: "Yawning",         category: "Action", difficulty: "easy" },
  { word: "Sneezing",        category: "Action", difficulty: "easy" },
  { word: "Climbing",        category: "Action", difficulty: "easy" },
  { word: "Cooking",         category: "Action", difficulty: "easy" },
  { word: "Surfing",         category: "Action", difficulty: "easy" },
  { word: "Skydiving",       category: "Action", difficulty: "easy" },
  { word: "Painting",        category: "Action", difficulty: "easy" },
  { word: "Shrugging",       category: "Action", difficulty: "easy" },
  { word: "Knitting",        category: "Action", difficulty: "easy" },
  { word: "Meditating",      category: "Action", difficulty: "easy" },
  // Medium
  { word: "Procrastinating", category: "Action", difficulty: "medium" },
  { word: "Negotiating",     category: "Action", difficulty: "medium" },
  { word: "Improvising",     category: "Action", difficulty: "medium" },
  { word: "Hallucinating",   category: "Action", difficulty: "medium" },
  { word: "Synchronising",   category: "Action", difficulty: "medium" },
  { word: "Eavesdropping",   category: "Action", difficulty: "medium" },
  { word: "Pickpocketing",   category: "Action", difficulty: "medium" },
  { word: "Lip Reading",     category: "Action", difficulty: "medium" },
  { word: "Ventriloquism",   category: "Action", difficulty: "medium" },
  { word: "Taxidermy",       category: "Action", difficulty: "medium" },
  // Hard
  { word: "Defenestrating",  category: "Action", difficulty: "hard" },
  { word: "Terraforming",    category: "Action", difficulty: "hard" },
  { word: "Defibrillating",  category: "Action", difficulty: "hard" },
  { word: "Circumnavigating",category: "Action", difficulty: "hard" },
  { word: "Gerrymandering",  category: "Action", difficulty: "hard" },

  // ─── WORLD ────────────────────────────────────────────────────────────────
  // Easy
  { word: "France",          category: "World", difficulty: "easy" },
  { word: "Amazon River",    category: "World", difficulty: "easy" },
  { word: "Sahara Desert",   category: "World", difficulty: "easy" },
  { word: "Mount Everest",   category: "World", difficulty: "easy" },
  { word: "New York City",   category: "World", difficulty: "easy" },
  { word: "Eiffel Tower",    category: "World", difficulty: "easy" },
  { word: "Tokyo",           category: "World", difficulty: "easy" },
  { word: "Antarctica",      category: "World", difficulty: "easy" },
  { word: "Colosseum",       category: "World", difficulty: "easy" },
  { word: "Nile River",      category: "World", difficulty: "easy" },
  { word: "Grand Canyon",    category: "World", difficulty: "easy" },
  { word: "Taj Mahal",       category: "World", difficulty: "easy" },
  { word: "Silicon Valley",  category: "World", difficulty: "easy" },
  { word: "Bermuda Triangle",category: "World", difficulty: "easy" },
  // Medium
  { word: "Machu Picchu",    category: "World", difficulty: "medium" },
  { word: "Patagonia",       category: "World", difficulty: "medium" },
  { word: "Equator",         category: "World", difficulty: "medium" },
  { word: "Strait of Gibraltar", category: "World", difficulty: "medium" },
  { word: "Dead Sea",        category: "World", difficulty: "medium" },
  { word: "Galapagos Islands", category: "World", difficulty: "medium" },
  { word: "Mariana Trench",  category: "World", difficulty: "medium" },
  { word: "Mesopotamia",     category: "World", difficulty: "medium" },
  { word: "Zanzibar",        category: "World", difficulty: "medium" },
  { word: "Gobi Desert",     category: "World", difficulty: "medium" },
  // Hard
  { word: "Dardanelles",     category: "World", difficulty: "hard" },
  { word: "Transylvania",    category: "World", difficulty: "hard" },
  { word: "Svalbard",        category: "World", difficulty: "hard" },
  { word: "Khyber Pass",     category: "World", difficulty: "hard" },
  { word: "Tropic of Cancer",category: "World", difficulty: "hard" },

  // ─── RANDOM ───────────────────────────────────────────────────────────────
  // Easy
  { word: "Birthday Party",  category: "Random", difficulty: "easy" },
  { word: "Social Media",    category: "Random", difficulty: "easy" },
  { word: "Traffic Jam",     category: "Random", difficulty: "easy" },
  { word: "Credit Card",     category: "Random", difficulty: "easy" },
  { word: "Password",        category: "Random", difficulty: "easy" },
  { word: "Deadline",        category: "Random", difficulty: "easy" },
  { word: "Salary",          category: "Random", difficulty: "easy" },
  { word: "Gossip",          category: "Random", difficulty: "easy" },
  { word: "Interview",       category: "Random", difficulty: "easy" },
  { word: "First Date",      category: "Random", difficulty: "easy" },
  { word: "Jet Lag",         category: "Random", difficulty: "easy" },
  { word: "Nostalgia",       category: "Random", difficulty: "easy" },
  { word: "Hangover",        category: "Random", difficulty: "easy" },
  { word: "Ghosting",        category: "Random", difficulty: "easy" },
  // Medium
  { word: "Cognitive Bias",  category: "Random", difficulty: "medium" },
  { word: "Sunk Cost",       category: "Random", difficulty: "medium" },
  { word: "Echo Chamber",    category: "Random", difficulty: "medium" },
  { word: "Imposter Syndrome", category: "Random", difficulty: "medium" },
  { word: "Gaslighting",     category: "Random", difficulty: "medium" },
  { word: "Gamification",    category: "Random", difficulty: "medium" },
  { word: "Dark Pattern",    category: "Random", difficulty: "medium" },
  { word: "Filter Bubble",   category: "Random", difficulty: "medium" },
  { word: "Greenwashing",    category: "Random", difficulty: "medium" },
  // Hard
  { word: "Counterfactual",  category: "Random", difficulty: "hard" },
  { word: "Epistemology",    category: "Random", difficulty: "hard" },
  { word: "Ontology",        category: "Random", difficulty: "hard" },
  { word: "Solipsism",       category: "Random", difficulty: "hard" },
  { word: "Hermeneutics",    category: "Random", difficulty: "hard" },

  // ─── 150 CARD EXPANSION ───────────────────────────────────────────────────
  // Object (25 new cards)
  { word: "Screwdriver", category: "Object", difficulty: "easy" },
  { word: "Hammer", category: "Object", difficulty: "easy" },
  { word: "Briefcase", category: "Object", difficulty: "easy" },
  { word: "Water Bottle", category: "Object", difficulty: "easy" },
  { word: "Keyring", category: "Object", difficulty: "easy" },
  { word: "Notebook", category: "Object", difficulty: "easy" },
  { word: "Headlight", category: "Object", difficulty: "easy" },
  { word: "Suitcase", category: "Object", difficulty: "easy" },
  { word: "Desk Lamp", category: "Object", difficulty: "easy" },
  { word: "Umbrella Stand", category: "Object", difficulty: "easy" },
  { word: "Barometer", category: "Object", difficulty: "medium" },
  { word: "Kettlebell", category: "Object", difficulty: "medium" },
  { word: "Magnifying Glass", category: "Object", difficulty: "medium" },
  { word: "Solder Iron", category: "Object", difficulty: "medium" },
  { word: "Tuning Fork", category: "Object", difficulty: "medium" },
  { word: "Prism", category: "Object", difficulty: "medium" },
  { word: "Microphone", category: "Object", difficulty: "medium" },
  { word: "Projector", category: "Object", difficulty: "medium" },
  { word: "Calculator", category: "Object", difficulty: "medium" },
  { word: "Tripod", category: "Object", difficulty: "medium" },
  { word: "Sextant", category: "Object", difficulty: "hard" },
  { word: "Spectrometer", category: "Object", difficulty: "hard" },
  { word: "Chronometer", category: "Object", difficulty: "hard" },
  { word: "Seismograph", category: "Object", difficulty: "hard" },
  { word: "Goniometer", category: "Object", difficulty: "hard" },

  // Nature (25 new cards)
  { word: "Sunflower", category: "Nature", difficulty: "easy" },
  { word: "Breeze", category: "Nature", difficulty: "easy" },
  { word: "Canyon", category: "Nature", difficulty: "easy" },
  { word: "Waterfall", category: "Nature", difficulty: "easy" },
  { word: "Forest", category: "Nature", difficulty: "easy" },
  { word: "Pebble", category: "Nature", difficulty: "easy" },
  { word: "Caterpillar", category: "Nature", difficulty: "easy" },
  { word: "Dragonfly", category: "Nature", difficulty: "easy" },
  { word: "Jellyfish", category: "Nature", difficulty: "easy" },
  { word: "Seashell", category: "Nature", difficulty: "easy" },
  { word: "Photosynthesis", category: "Nature", difficulty: "medium" },
  { word: "Tectonic Plates", category: "Nature", difficulty: "medium" },
  { word: "Pollination", category: "Nature", difficulty: "medium" },
  { word: "Metamorphosis", category: "Nature", difficulty: "medium" },
  { word: "Geyser", category: "Nature", difficulty: "medium" },
  { word: "Canopy", category: "Nature", difficulty: "medium" },
  { word: "Ecosystem", category: "Nature", difficulty: "medium" },
  { word: "Estuary", category: "Nature", difficulty: "medium" },
  { word: "Chaparral", category: "Nature", difficulty: "medium" },
  { word: "Deciduous Forest", category: "Nature", difficulty: "medium" },
  { word: "Hydrothermal Vent", category: "Nature", difficulty: "hard" },
  { word: "Mycelium", category: "Nature", difficulty: "hard" },
  { word: "Symbiosis", category: "Nature", difficulty: "hard" },
  { word: "Parthenogenesis", category: "Nature", difficulty: "hard" },
  { word: "Angiosperm", category: "Nature", difficulty: "hard" },

  // Person (25 new cards)
  { word: "Isaac Newton", category: "Person", difficulty: "easy" },
  { word: "Abraham Lincoln", category: "Person", difficulty: "easy" },
  { word: "Frida Kahlo", category: "Person", difficulty: "easy" },
  { word: "Amelia Earhart", category: "Person", difficulty: "easy" },
  { word: "Vincent van Gogh", category: "Person", difficulty: "easy" },
  { word: "Stephen Hawking", category: "Person", difficulty: "easy" },
  { word: "Malala Yousafzai", category: "Person", difficulty: "easy" },
  { word: "Rosa Parks", category: "Person", difficulty: "easy" },
  { word: "Winston Churchill", category: "Person", difficulty: "easy" },
  { word: "Charles Darwin", category: "Person", difficulty: "easy" },
  { word: "Jane Austen", category: "Person", difficulty: "medium" },
  { word: "Marco Polo", category: "Person", difficulty: "medium" },
  { word: "Thomas Edison", category: "Person", difficulty: "medium" },
  { word: "Alexander Fleming", category: "Person", difficulty: "medium" },
  { word: "Srinivasa Ramanujan", category: "Person", difficulty: "medium" },
  { word: "Marie Antoinette", category: "Person", difficulty: "medium" },
  { word: "Gautama Buddha", category: "Person", difficulty: "medium" },
  { word: "Julius Caesar", category: "Person", difficulty: "medium" },
  { word: "Harriet Tubman", category: "Person", difficulty: "medium" },
  { word: "John F. Kennedy", category: "Person", difficulty: "medium" },
  { word: "Alan Turing", category: "Person", difficulty: "hard" },
  { word: "Aristotle", category: "Person", difficulty: "hard" },
  { word: "Plato", category: "Person", difficulty: "hard" },
  { word: "Alexander the Great", category: "Person", difficulty: "hard" },
  { word: "Genghis Khan", category: "Person", difficulty: "hard" },

  // Action (25 new cards)
  { word: "Walking", category: "Action", difficulty: "easy" },
  { word: "Writing", category: "Action", difficulty: "easy" },
  { word: "Singing", category: "Action", difficulty: "easy" },
  { word: "Dancing", category: "Action", difficulty: "easy" },
  { word: "Gardening", category: "Action", difficulty: "easy" },
  { word: "Fishing", category: "Action", difficulty: "easy" },
  { word: "Smiling", category: "Action", difficulty: "easy" },
  { word: "Laughing", category: "Action", difficulty: "easy" },
  { word: "Crying", category: "Action", difficulty: "easy" },
  { word: "Sailing", category: "Action", difficulty: "easy" },
  { word: "Tightrope Walking", category: "Action", difficulty: "medium" },
  { word: "Rock Climbing", category: "Action", difficulty: "medium" },
  { word: "Scuba Diving", category: "Action", difficulty: "medium" },
  { word: "Woodcarving", category: "Action", difficulty: "medium" },
  { word: "Skateboarding", category: "Action", difficulty: "medium" },
  { word: "Origami", category: "Action", difficulty: "medium" },
  { word: "Birdwatching", category: "Action", difficulty: "medium" },
  { word: "Potholing", category: "Action", difficulty: "medium" },
  { word: "Stargazing", category: "Action", difficulty: "medium" },
  { word: "Bungee Jumping", category: "Action", difficulty: "medium" },
  { word: "Deciphering", category: "Action", difficulty: "hard" },
  { word: "Triangulating", category: "Action", difficulty: "hard" },
  { word: "Understudying", category: "Action", difficulty: "hard" },
  { word: "Mimicking", category: "Action", difficulty: "hard" },
  { word: "Synchronizing", category: "Action", difficulty: "hard" },

  // World (25 new cards)
  { word: "Great Wall of China", category: "World", difficulty: "easy" },
  { word: "Statue of Liberty", category: "World", difficulty: "easy" },
  { word: "Mount Kilimanjaro", category: "World", difficulty: "easy" },
  { word: "Great Barrier Reef", category: "World", difficulty: "easy" },
  { word: "Niagara Falls", category: "World", difficulty: "easy" },
  { word: "Stonehenge", category: "World", difficulty: "easy" },
  { word: "Mount Fuji", category: "World", difficulty: "easy" },
  { word: "Petra", category: "World", difficulty: "easy" },
  { word: "Loch Ness", category: "World", difficulty: "easy" },
  { word: "Sydney Opera House", category: "World", difficulty: "easy" },
  { word: "Angkor Wat", category: "World", difficulty: "medium" },
  { word: "Easter Island", category: "World", difficulty: "medium" },
  { word: "Kremlin", category: "World", difficulty: "medium" },
  { word: "Acropolis", category: "World", difficulty: "medium" },
  { word: "Versailles Palace", category: "World", difficulty: "medium" },
  { word: "Alhambra", category: "World", difficulty: "medium" },
  { word: "Chichen Itza", category: "World", difficulty: "medium" },
  { word: "Giant's Causeway", category: "World", difficulty: "medium" },
  { word: "Yellowstone National Park", category: "World", difficulty: "medium" },
  { word: "Panama Canal", category: "World", difficulty: "medium" },
  { word: "Mariana Trench", category: "World", difficulty: "hard" },
  { word: "Strait of Malacca", category: "World", difficulty: "hard" },
  { word: "Surtsey Island", category: "World", difficulty: "hard" },
  { word: "Danakil Depression", category: "World", difficulty: "hard" },
  { word: "Socotra Archipelago", category: "World", difficulty: "hard" },

  // Random (25 new cards)
  { word: "Birthday Cake", category: "Random", difficulty: "easy" },
  { word: "Roller Coaster", category: "Random", difficulty: "easy" },
  { word: "High Five", category: "Random", difficulty: "easy" },
  { word: "Movie Theatre", category: "Random", difficulty: "easy" },
  { word: "Supermarket", category: "Random", difficulty: "easy" },
  { word: "Ice Cream Cone", category: "Random", difficulty: "easy" },
  { word: "Coffee Shop", category: "Random", difficulty: "easy" },
  { word: "Library Card", category: "Random", difficulty: "easy" },
  { word: "Passport Control", category: "Random", difficulty: "easy" },
  { word: "Board Game", category: "Random", difficulty: "easy" },
  { word: "Virtual Reality", category: "Random", difficulty: "medium" },
  { word: "Artificial Intelligence", category: "Random", difficulty: "medium" },
  { word: "Blockchain", category: "Random", difficulty: "medium" },
  { word: "Quantum Computing", category: "Random", difficulty: "medium" },
  { word: "Cryptography", category: "Random", difficulty: "medium" },
  { word: "Machine Learning", category: "Random", difficulty: "medium" },
  { word: "Dark Matter", category: "Random", difficulty: "medium" },
  { word: "Theory of Relativity", category: "Random", difficulty: "medium" },
  { word: "Cyber Security", category: "Random", difficulty: "medium" },
  { word: "Global Warming", category: "Random", difficulty: "medium" },
  { word: "Schrodinger's Cat", category: "Random", difficulty: "hard" },
  { word: "Event Horizon", category: "Random", difficulty: "hard" },
  { word: "Chaos Theory", category: "Random", difficulty: "hard" },
  { word: "Fibonacci Sequence", category: "Random", difficulty: "hard" },
  { word: "Turing Test", category: "Random", difficulty: "hard" },

  // ─── 60 EASY WORDS EXPANSION ──────────────────────────────────────────────
  // Object
  { word: "Coffee Mug", category: "Object", difficulty: "easy" },
  { word: "Wristwatch", category: "Object", difficulty: "easy" },
  { word: "Pencil Case", category: "Object", difficulty: "easy" },
  { word: "Watering Can", category: "Object", difficulty: "easy" },
  { word: "Computer Mouse", category: "Object", difficulty: "easy" },
  { word: "Frying Pan", category: "Object", difficulty: "easy" },
  { word: "Door Key", category: "Object", difficulty: "easy" },
  { word: "Sleeping Bag", category: "Object", difficulty: "easy" },
  { word: "Photo Frame", category: "Object", difficulty: "easy" },
  { word: "Wall Clock", category: "Object", difficulty: "easy" },

  // Nature
  { word: "Ladybug", category: "Nature", difficulty: "easy" },
  { word: "Pinecone", category: "Nature", difficulty: "easy" },
  { word: "Spiderweb", category: "Nature", difficulty: "easy" },
  { word: "Maple Leaf", category: "Nature", difficulty: "easy" },
  { word: "Sandcastle", category: "Nature", difficulty: "easy" },
  { word: "Snowflake", category: "Nature", difficulty: "easy" },
  { word: "Acorn", category: "Nature", difficulty: "easy" },
  { word: "Dandelion", category: "Nature", difficulty: "easy" },
  { word: "Tadpole", category: "Nature", difficulty: "easy" },
  { word: "Butterfly", category: "Nature", difficulty: "easy" },

  // Person
  { word: "Teacher", category: "Person", difficulty: "easy" },
  { word: "Doctor", category: "Person", difficulty: "easy" },
  { word: "Singer", category: "Person", difficulty: "easy" },
  { word: "Farmer", category: "Person", difficulty: "easy" },
  { word: "Pilot", category: "Person", difficulty: "easy" },
  { word: "Artist", category: "Person", difficulty: "easy" },
  { word: "Police Officer", category: "Person", difficulty: "easy" },
  { word: "Writer", category: "Person", difficulty: "easy" },
  { word: "Actor", category: "Person", difficulty: "easy" },
  { word: "Baker", category: "Person", difficulty: "easy" },

  // Action
  { word: "Clapping", category: "Action", difficulty: "easy" },
  { word: "Jumping", category: "Action", difficulty: "easy" },
  { word: "Eating", category: "Action", difficulty: "easy" },
  { word: "Drinking", category: "Action", difficulty: "easy" },
  { word: "Sleeping", category: "Action", difficulty: "easy" },
  { word: "Reading", category: "Action", difficulty: "easy" },
  { word: "Talking", category: "Action", difficulty: "easy" },
  { word: "Waving", category: "Action", difficulty: "easy" },
  { word: "Throwing", category: "Action", difficulty: "easy" },
  { word: "Catching", category: "Action", difficulty: "easy" },

  // World
  { word: "London", category: "World", difficulty: "easy" },
  { word: "Paris", category: "World", difficulty: "easy" },
  { word: "Rome", category: "World", difficulty: "easy" },
  { word: "China", category: "World", difficulty: "easy" },
  { word: "Canada", category: "World", difficulty: "easy" },
  { word: "Egypt", category: "World", difficulty: "easy" },
  { word: "Australia", category: "World", difficulty: "easy" },
  { word: "Mexico", category: "World", difficulty: "easy" },
  { word: "Brazil", category: "World", difficulty: "easy" },
  { word: "India", category: "World", difficulty: "easy" },

  // Random
  { word: "Ice Cream", category: "Random", difficulty: "easy" },
  { word: "Pizza Slice", category: "Random", difficulty: "easy" },
  { word: "Hot Dog", category: "Random", difficulty: "easy" },
  { word: "Popcorn", category: "Random", difficulty: "easy" },
  { word: "Soda Can", category: "Random", difficulty: "easy" },
  { word: "Balloon", category: "Random", difficulty: "easy" },
  { word: "Gift Box", category: "Random", difficulty: "easy" },
  { word: "Bicycle Helmet", category: "Random", difficulty: "easy" },
  { word: "Teddy Bear", category: "Random", difficulty: "easy" },
  { word: "Sunglasses Case", category: "Random", difficulty: "easy" },

  // ─── 240 CARD EXPANSION (120 EASY, 120 HARD) ──────────────────────────────
  // Object - Easy (20)
  { word: "Cardboard Box", category: "Object", difficulty: "easy" },
  { word: "Plastic Spoon", category: "Object", difficulty: "easy" },
  { word: "Toothpick", category: "Object", difficulty: "easy" },
  { word: "Coffee Cup", category: "Object", difficulty: "easy" },
  { word: "Baking Tray", category: "Object", difficulty: "easy" },
  { word: "Water Glass", category: "Object", difficulty: "easy" },
  { word: "Paper Plate", category: "Object", difficulty: "easy" },
  { word: "Pencil Sharpener", category: "Object", difficulty: "easy" },
  { word: "School Backpack", category: "Object", difficulty: "easy" },
  { word: "Bath Towel", category: "Object", difficulty: "easy" },
  { word: "T-Shirt", category: "Object", difficulty: "easy" },
  { word: "Tennis Racket", category: "Object", difficulty: "easy" },
  { word: "Baseball Bat", category: "Object", difficulty: "easy" },
  { word: "Door Handle", category: "Object", difficulty: "easy" },
  { word: "Window Pane", category: "Object", difficulty: "easy" },
  { word: "Car Key", category: "Object", difficulty: "easy" },
  { word: "Postcard", category: "Object", difficulty: "easy" },
  { word: "Guitar String", category: "Object", difficulty: "easy" },
  { word: "Screwing Bolt", category: "Object", difficulty: "easy" },
  { word: "Ironing Board", category: "Object", difficulty: "easy" },
  // Object - Hard (20)
  { word: "Caliper", category: "Object", difficulty: "hard" },
  { word: "Pyrometer", category: "Object", difficulty: "hard" },
  { word: "Manometer", category: "Object", difficulty: "hard" },
  { word: "Anemometer", category: "Object", difficulty: "hard" },
  { word: "Hygrometer", category: "Object", difficulty: "hard" },
  { word: "Tachymeter", category: "Object", difficulty: "hard" },
  { word: "Clinometer", category: "Object", difficulty: "hard" },
  { word: "Refractometer", category: "Object", difficulty: "hard" },
  { word: "Polarimeter", category: "Object", difficulty: "hard" },
  { word: "Microtome", category: "Object", difficulty: "hard" },
  { word: "Interferometer", category: "Object", difficulty: "hard" },
  { word: "Spectrophotometer", category: "Object", difficulty: "hard" },
  { word: "Theodolite", category: "Object", difficulty: "hard" },
  { word: "Planisphere", category: "Object", difficulty: "hard" },
  { word: "Armillary Sphere", category: "Object", difficulty: "hard" },
  { word: "Sundial Gnomon", category: "Object", difficulty: "hard" },
  { word: "Electrochemical Cell", category: "Object", difficulty: "hard" },
  { word: "Piezoelectric Sensor", category: "Object", difficulty: "hard" },
  { word: "Stroboscope", category: "Object", difficulty: "hard" },
  { word: "Magnetometer", category: "Object", difficulty: "hard" },

  // Nature - Easy (20)
  { word: "Maple Leaf", category: "Nature", difficulty: "easy" },
  { word: "Oak Acorn", category: "Nature", difficulty: "easy" },
  { word: "Apple Tree", category: "Nature", difficulty: "easy" },
  { word: "Rose Petal", category: "Nature", difficulty: "easy" },
  { word: "Pine Tree", category: "Nature", difficulty: "easy" },
  { word: "Raindrop", category: "Nature", difficulty: "easy" },
  { word: "Snowflake", category: "Nature", difficulty: "easy" },
  { word: "Mud Puddle", category: "Nature", difficulty: "easy" },
  { word: "Sand Dune", category: "Nature", difficulty: "easy" },
  { word: "River Bank", category: "Nature", difficulty: "easy" },
  { word: "Grass Patch", category: "Nature", difficulty: "easy" },
  { word: "Bird Nest", category: "Nature", difficulty: "easy" },
  { word: "Spider Web", category: "Nature", difficulty: "easy" },
  { word: "Beehive", category: "Nature", difficulty: "easy" },
  { word: "Ant Hill", category: "Nature", difficulty: "easy" },
  { word: "Caterpillar", category: "Nature", difficulty: "easy" },
  { word: "Ladybug", category: "Nature", difficulty: "easy" },
  { word: "Firefly", category: "Nature", difficulty: "easy" },
  { word: "Earthworm", category: "Nature", difficulty: "easy" },
  { word: "Squirrel", category: "Nature", difficulty: "easy" },
  // Nature - Hard (20)
  { word: "Xerophyte", category: "Nature", difficulty: "hard" },
  { word: "Halophyte", category: "Nature", difficulty: "hard" },
  { word: "Epiphyte", category: "Nature", difficulty: "hard" },
  { word: "Mycorrhiza", category: "Nature", difficulty: "hard" },
  { word: "Nastic Movement", category: "Nature", difficulty: "hard" },
  { word: "Gravitropism", category: "Nature", difficulty: "hard" },
  { word: "Chemotropism", category: "Nature", difficulty: "hard" },
  { word: "Photoperiodism", category: "Nature", difficulty: "hard" },
  { word: "Eutrophication", category: "Nature", difficulty: "hard" },
  { word: "Bioaccumulation", category: "Nature", difficulty: "hard" },
  { word: "Biomagnification", category: "Nature", difficulty: "hard" },
  { word: "Endosymbiosis", category: "Nature", difficulty: "hard" },
  { word: "Speciation", category: "Nature", difficulty: "hard" },
  { word: "Adaptive Radiation", category: "Nature", difficulty: "hard" },
  { word: "Polyploidy", category: "Nature", difficulty: "hard" },
  { word: "Epigenetics", category: "Nature", difficulty: "hard" },
  { word: "Phenotypic Plasticity", category: "Nature", difficulty: "hard" },
  { word: "Trophic Cascade", category: "Nature", difficulty: "hard" },
  { word: "Climax Community", category: "Nature", difficulty: "hard" },
  { word: "Keystone Species", category: "Nature", difficulty: "hard" },

  // Person - Easy (20)
  { word: "Mail Carrier", category: "Person", difficulty: "easy" },
  { word: "Bus Driver", category: "Person", difficulty: "easy" },
  { word: "Taxi Driver", category: "Person", difficulty: "easy" },
  { word: "Shop Keeper", category: "Person", difficulty: "easy" },
  { word: "Librarian", category: "Person", difficulty: "easy" },
  { word: "Dentist", category: "Person", difficulty: "easy" },
  { word: "Veterinarian", category: "Person", difficulty: "easy" },
  { word: "Pharmacist", category: "Person", difficulty: "easy" },
  { word: "Bank Teller", category: "Person", difficulty: "easy" },
  { word: "Cashier", category: "Person", difficulty: "easy" },
  { word: "Receptionist", category: "Person", difficulty: "easy" },
  { word: "Security Guard", category: "Person", difficulty: "easy" },
  { word: "Lifeguard", category: "Person", difficulty: "easy" },
  { word: "Flight Attendant", category: "Person", difficulty: "easy" },
  { word: "Clean-up Crew", category: "Person", difficulty: "easy" },
  { word: "Gardener", category: "Person", difficulty: "easy" },
  { word: "Plumber", category: "Person", difficulty: "easy" },
  { word: "Electrician", category: "Person", difficulty: "easy" },
  { word: "Carpenter", category: "Person", difficulty: "easy" },
  { word: "Mechanic", category: "Person", difficulty: "easy" },
  // Person - Hard (20)
  { word: "Herodotus", category: "Person", difficulty: "hard" },
  { word: "Thucydides", category: "Person", difficulty: "hard" },
  { word: "Eratosthenes", category: "Person", difficulty: "hard" },
  { word: "Aristarchus", category: "Person", difficulty: "hard" },
  { word: "Hipparchus", category: "Person", difficulty: "hard" },
  { word: "Ptolemy", category: "Person", difficulty: "hard" },
  { word: "Vesalius", category: "Person", difficulty: "hard" },
  { word: "Harvey", category: "Person", difficulty: "hard" },
  { word: "Lavoisier", category: "Person", difficulty: "hard" },
  { word: "Mendeleev", category: "Person", difficulty: "hard" },
  { word: "Pasteur", category: "Person", difficulty: "hard" },
  { word: "Koch", category: "Person", difficulty: "hard" },
  { word: "Planck", category: "Person", difficulty: "hard" },
  { word: "Schrödinger", category: "Person", difficulty: "hard" },
  { word: "Heisenberg", category: "Person", difficulty: "hard" },
  { word: "Dirac", category: "Person", difficulty: "hard" },
  { word: "Feynman", category: "Person", difficulty: "hard" },
  { word: "Gell-Mann", category: "Person", difficulty: "hard" },
  { word: "Watson and Crick", category: "Person", difficulty: "hard" },
  { word: "Rosalind Franklin", category: "Person", difficulty: "hard" },

  // Action - Easy (20)
  { word: "Walking the Dog", category: "Action", difficulty: "easy" },
  { word: "Brushing Teeth", category: "Action", difficulty: "easy" },
  { word: "Washing Dishes", category: "Action", difficulty: "easy" },
  { word: "Making the Bed", category: "Action", difficulty: "easy" },
  { word: "Sweeping the Floor", category: "Action", difficulty: "easy" },
  { word: "Dusting Furniture", category: "Action", difficulty: "easy" },
  { word: "Watering Plants", category: "Action", difficulty: "easy" },
  { word: "Folding Clothes", category: "Action", difficulty: "easy" },
  { word: "Tying Shoes", category: "Action", difficulty: "easy" },
  { word: "Zipping a Jacket", category: "Action", difficulty: "easy" },
  { word: "Opening a Box", category: "Action", difficulty: "easy" },
  { word: "Writing a Letter", category: "Action", difficulty: "easy" },
  { word: "Reading a Book", category: "Action", difficulty: "easy" },
  { word: "Drawing a Picture", category: "Action", difficulty: "easy" },
  { word: "Singing a Song", category: "Action", difficulty: "easy" },
  { word: "Playing a Game", category: "Action", difficulty: "easy" },
  { word: "Taking a Photo", category: "Action", difficulty: "easy" },
  { word: "Watching TV", category: "Action", difficulty: "easy" },
  { word: "Listening to Music", category: "Action", difficulty: "easy" },
  { word: "Talking on the Phone", category: "Action", difficulty: "easy" },
  // Action - Hard (20)
  { word: "Extrapolating", category: "Action", difficulty: "hard" },
  { word: "Interpolating", category: "Action", difficulty: "hard" },
  { word: "Substantiating", category: "Action", difficulty: "hard" },
  { word: "Corroborating", category: "Action", difficulty: "hard" },
  { word: "Ameliorating", category: "Action", difficulty: "hard" },
  { word: "Exacerbating", category: "Action", difficulty: "hard" },
  { word: "Obfuscating", category: "Action", difficulty: "hard" },
  { word: "Elucidating", category: "Action", difficulty: "hard" },
  { word: "Equivocating", category: "Action", difficulty: "hard" },
  { word: "Prevaricating", category: "Action", difficulty: "hard" },
  { word: "Tergiversating", category: "Action", difficulty: "hard" },
  { word: "Vacillating", category: "Action", difficulty: "hard" },
  { word: "Oscillating", category: "Action", difficulty: "hard" },
  { word: "Fluctuating", category: "Action", difficulty: "hard" },
  { word: "Undulating", category: "Action", difficulty: "hard" },
  { word: "Scintillating", category: "Action", difficulty: "hard" },
  { word: "Coruscating", category: "Action", difficulty: "hard" },
  { word: "Reverberating", category: "Action", difficulty: "hard" },
  { word: "Resonating", category: "Action", difficulty: "hard" },
  { word: "Capitulating", category: "Action", difficulty: "hard" },

  // World - Easy (20)
  { word: "Mount Rushmore", category: "World", difficulty: "easy" },
  { word: "Golden Gate Bridge", category: "World", difficulty: "easy" },
  { word: "Empire State Building", category: "World", difficulty: "easy" },
  { word: "Big Ben", category: "World", difficulty: "easy" },
  { word: "Tower Bridge", category: "World", difficulty: "easy" },
  { word: "Stonehenge", category: "World", difficulty: "easy" },
  { word: "Loch Ness", category: "World", difficulty: "easy" },
  { word: "Giant's Causeway", category: "World", difficulty: "easy" },
  { word: "Eiffel Tower", category: "World", difficulty: "easy" },
  { word: "Louvre Museum", category: "World", difficulty: "easy" },
  { word: "Notre Dame", category: "World", difficulty: "easy" },
  { word: "Leaning Tower of Pisa", category: "World", difficulty: "easy" },
  { word: "Venice Canals", category: "World", difficulty: "easy" },
  { word: "Colosseum", category: "World", difficulty: "easy" },
  { word: "Vatican City", category: "World", difficulty: "easy" },
  { word: "Acropolis", category: "World", difficulty: "easy" },
  { word: "Parthenon", category: "World", difficulty: "easy" },
  { word: "Kremlin", category: "World", difficulty: "easy" },
  { word: "Red Square", category: "World", difficulty: "easy" },
  { word: "Taj Mahal", category: "World", difficulty: "easy" },
  // World - Hard (20)
  { word: "Okavango Delta", category: "World", difficulty: "hard" },
  { word: "Danakil Depression", category: "World", difficulty: "hard" },
  { word: "Dallol Volcano", category: "World", difficulty: "hard" },
  { word: "Lake Natron", category: "World", difficulty: "hard" },
  { word: "Lake Baikal", category: "World", difficulty: "hard" },
  { word: "Lake Titicaca", category: "World", difficulty: "hard" },
  { word: "Lake Tanganyika", category: "World", difficulty: "hard" },
  { word: "Lake Victoria", category: "World", difficulty: "hard" },
  { word: "Lake Malawi", category: "World", difficulty: "hard" },
  { word: "Caspian Sea", category: "World", difficulty: "hard" },
  { word: "Aral Sea", category: "World", difficulty: "hard" },
  { word: "Dead Sea", category: "World", difficulty: "hard" },
  { word: "Red Sea", category: "World", difficulty: "hard" },
  { word: "Black Sea", category: "World", difficulty: "hard" },
  { word: "Baltic Sea", category: "World", difficulty: "hard" },
  { word: "Mediterranean Sea", category: "World", difficulty: "hard" },
  { word: "Caribbean Sea", category: "World", difficulty: "hard" },
  { word: "Gulf of Mexico", category: "World", difficulty: "hard" },
  { word: "Persian Gulf", category: "World", difficulty: "hard" },
  { word: "Strait of Hormuz", category: "World", difficulty: "hard" },

  // Random - Easy (20)
  { word: "Popcorn Bucket", category: "Random", difficulty: "easy" },
  { word: "Cotton Candy", category: "Random", difficulty: "easy" },
  { word: "Ferris Wheel", category: "Random", difficulty: "easy" },
  { word: "Hot Air Balloon", category: "Random", difficulty: "easy" },
  { word: "Paper Airplane", category: "Random", difficulty: "easy" },
  { word: "Magic Trick", category: "Random", difficulty: "easy" },
  { word: "Card Trick", category: "Random", difficulty: "easy" },
  { word: "Coin Toss", category: "Random", difficulty: "easy" },
  { word: "Board Game", category: "Random", difficulty: "easy" },
  { word: "Card Game", category: "Random", difficulty: "easy" },
  { word: "Video Game", category: "Random", difficulty: "easy" },
  { word: "Mobile Phone", category: "Random", difficulty: "easy" },
  { word: "Smart Watch", category: "Random", difficulty: "easy" },
  { word: "Laptop Computer", category: "Random", difficulty: "easy" },
  { word: "Tablet Device", category: "Random", difficulty: "easy" },
  { word: "Ear Buds", category: "Random", difficulty: "easy" },
  { word: "Power Bank", category: "Random", difficulty: "easy" },
  { word: "Charging Cable", category: "Random", difficulty: "easy" },
  { word: "USB Drive", category: "Random", difficulty: "easy" },
  { word: "Memory Card", category: "Random", difficulty: "easy" },
  // Random - Hard (20)
  { word: "Cognitive Dissonance", category: "Random", difficulty: "hard" },
  { word: "Confirmation Bias", category: "Random", difficulty: "hard" },
  { word: "Hindsight Bias", category: "Random", difficulty: "hard" },
  { word: "Availability Heuristic", category: "Random", difficulty: "hard" },
  { word: "Representativeness Heuristic", category: "Random", difficulty: "hard" },
  { word: "Anchoring Effect", category: "Random", difficulty: "hard" },
  { word: "Framing Effect", category: "Random", difficulty: "hard" },
  { word: "Loss Aversion", category: "Random", difficulty: "hard" },
  { word: "Sunk Cost Fallacy", category: "Random", difficulty: "hard" },
  { word: "Status Quo Bias", category: "Random", difficulty: "hard" },
  { word: "Endowment Effect", category: "Random", difficulty: "hard" },
  { word: "Hyperbolic Discounting", category: "Random", difficulty: "hard" },
  { word: "Intertemporal Choice", category: "Random", difficulty: "hard" },
  { word: "Bounded Rationality", category: "Random", difficulty: "hard" },
  { word: "Satisficing", category: "Random", difficulty: "hard" },
  { word: "Prospect Theory", category: "Random", difficulty: "hard" },
  { word: "Utility Function", category: "Random", difficulty: "hard" },
  { word: "Indifference Curve", category: "Random", difficulty: "hard" },
  { word: "Budget Constraint", category: "Random", difficulty: "hard" },
  { word: "Opportunity Cost", category: "Random", difficulty: "hard" },

  // ─── CLASSIC ARTICULATE RETRO CARDS (NOSTALGIA EXPANSION) ─────────────────────────
  { word: "Corkscrew", category: "Object", difficulty: "easy" },
  { word: "Lawnmower", category: "Object", difficulty: "easy" },
  { word: "Wheelbarrow", category: "Object", difficulty: "easy" },
  { word: "Fire Extinguisher", category: "Object", difficulty: "easy" },
  { word: "Paperclip", category: "Object", difficulty: "easy" },
  { word: "Teapot", category: "Object", difficulty: "easy" },
  { word: "Stethoscope", category: "Object", difficulty: "medium" },
  { word: "Mousetrap", category: "Object", difficulty: "easy" },
  { word: "Yo-Yo", category: "Object", difficulty: "easy" },
  { word: "Pogo Stick", category: "Object", difficulty: "easy" },
  { word: "Windmill", category: "Object", difficulty: "easy" },
  { word: "Lighthouse", category: "Object", difficulty: "easy" },
  { word: "Chandelier", category: "Object", difficulty: "medium" },
  { word: "Boomerang", category: "Object", difficulty: "easy" },
  { word: "Harmonica", category: "Object", difficulty: "easy" },
  { word: "Walkie-Talkie", category: "Object", difficulty: "easy" },
  { word: "Dustpan", category: "Object", difficulty: "easy" },
  { word: "Rolling Pin", category: "Object", difficulty: "easy" },
  { word: "Flyswatter", category: "Object", difficulty: "easy" },
  { word: "Trampoline", category: "Object", difficulty: "easy" },
  { word: "Submarine", category: "Object", difficulty: "easy" },
  { word: "Sewing Machine", category: "Object", difficulty: "easy" },
  { word: "Handcuffs", category: "Object", difficulty: "easy" },
  { word: "Parachute", category: "Object", difficulty: "easy" },
  { word: "Snowglobe", category: "Object", difficulty: "easy" },
  { word: "Rubber Duck", category: "Object", difficulty: "easy" },
  { word: "Safety Pin", category: "Object", difficulty: "easy" },
  { word: "Whistle", category: "Object", difficulty: "easy" },
  { word: "Clothespeg", category: "Object", difficulty: "easy" },
  { word: "Shoelace", category: "Object", difficulty: "easy" },
  { word: "Staple Remover", category: "Object", difficulty: "easy" },
  { word: "Bookmark", category: "Object", difficulty: "easy" },
  { word: "Nutcracker", category: "Object", difficulty: "easy" },
  { word: "Binoculars", category: "Object", difficulty: "easy" },
  { word: "Garden Hose", category: "Object", difficulty: "easy" },
  { word: "Plunger", category: "Object", difficulty: "easy" },
  { word: "Shopping Trolley", category: "Object", difficulty: "easy" },
  { word: "Toaster", category: "Object", difficulty: "easy" },
  { word: "Hairdryer", category: "Object", difficulty: "easy" },
  { word: "Colander", category: "Object", difficulty: "easy" },
  { word: "Swiss Army Knife", category: "Object", difficulty: "easy" },
  { word: "Corkboard", category: "Object", difficulty: "easy" },
  { word: "Lava Lamp", category: "Object", difficulty: "easy" },
  { word: "Flypaper", category: "Object", difficulty: "easy" },
  { word: "Bungee Cord", category: "Object", difficulty: "easy" },
  { word: "Slingshot", category: "Object", difficulty: "easy" },
  { word: "Crowbar", category: "Object", difficulty: "easy" },
  { word: "Walkman", category: "Object", difficulty: "medium" },
  { word: "Cassette Tape", category: "Object", difficulty: "easy" },
  { word: "Floppy Disk", category: "Object", difficulty: "easy" },
  { word: "Bowling Ball", category: "Object", difficulty: "easy" },
  { word: "Snorkel", category: "Object", difficulty: "easy" },
  { word: "Lifejacket", category: "Object", difficulty: "easy" },
  { word: "Hammock", category: "Object", difficulty: "easy" },
  { word: "Wind Chime", category: "Object", difficulty: "easy" },
  { word: "Dreamcatcher", category: "Object", difficulty: "easy" },
  { word: "Ukulele", category: "Object", difficulty: "easy" },
  { word: "Porthole", category: "Object", difficulty: "medium" },
  { word: "Anchor", category: "Object", difficulty: "easy" },
  { word: "Monocle", category: "Object", difficulty: "medium" },
  { word: "Toothpaste", category: "Object", difficulty: "easy" },
  { word: "Coffee Grinder", category: "Object", difficulty: "easy" },
  { word: "Meat Cleaver", category: "Object", difficulty: "medium" },
  { word: "Thermos", category: "Object", difficulty: "easy" },
  { word: "Paintbrush", category: "Object", difficulty: "easy" },
  { word: "Extension Cord", category: "Object", difficulty: "easy" },
  { word: "Bicycle Pump", category: "Object", difficulty: "easy" },
  { word: "Tape Measure", category: "Object", difficulty: "easy" },
  { word: "Bubble Wrap", category: "Object", difficulty: "easy" },
  { word: "Feather Duster", category: "Object", difficulty: "easy" },
  { word: "Padlock", category: "Object", difficulty: "easy" },
  { word: "Horseshoe", category: "Object", difficulty: "easy" },
  { word: "Boombox", category: "Object", difficulty: "easy" },
  { word: "Squeegee", category: "Object", difficulty: "easy" },
  { word: "Waffle Iron", category: "Object", difficulty: "easy" },
  { word: "Salt Shaker", category: "Object", difficulty: "easy" },
  { word: "Pepper Mill", category: "Object", difficulty: "easy" },
  { word: "Ice Cube Tray", category: "Object", difficulty: "easy" },
  { word: "Water Gun", category: "Object", difficulty: "easy" },
  { word: "Bicycle Bell", category: "Object", difficulty: "easy" },
  { word: "Fidget Spinner", category: "Object", difficulty: "easy" },
  { word: "Snowshoes", category: "Object", difficulty: "medium" },
  { word: "Windup Toy", category: "Object", difficulty: "easy" },
  { word: "Kaleidoscope", category: "Object", difficulty: "medium" },
  { word: "Paper Lantern", category: "Object", difficulty: "easy" },
  { word: "Glowstick", category: "Object", difficulty: "easy" },
  { word: "Magic Wand", category: "Object", difficulty: "easy" },
  { word: "Crystal Ball", category: "Object", difficulty: "easy" },
  { word: "Fortune Cookie", category: "Object", difficulty: "easy" },
  { word: "Pinata", category: "Object", difficulty: "easy" },
  { word: "Safety Goggles", category: "Object", difficulty: "easy" },
  { word: "Meat Thermometer", category: "Object", difficulty: "medium" },
  { word: "Chimpanzee", category: "Nature", difficulty: "easy" },
  { word: "Chameleon", category: "Nature", difficulty: "easy" },
  { word: "Kangaroo", category: "Nature", difficulty: "easy" },
  { word: "Blue Whale", category: "Nature", difficulty: "easy" },
  { word: "Mosquito", category: "Nature", difficulty: "easy" },
  { word: "Sea Turtle", category: "Nature", difficulty: "easy" },
  { word: "Hippopotamus", category: "Nature", difficulty: "easy" },
  { word: "Weeping Willow", category: "Nature", difficulty: "easy" },
  { word: "Redwood Tree", category: "Nature", difficulty: "easy" },
  { word: "Coral Reef", category: "Nature", difficulty: "easy" },
  { word: "Quicksand", category: "Nature", difficulty: "easy" },
  { word: "Lightning Bolt", category: "Nature", difficulty: "easy" },
  { word: "Solar Eclipse", category: "Nature", difficulty: "easy" },
  { word: "Oasis", category: "Nature", difficulty: "easy" },
  { word: "Swamp", category: "Nature", difficulty: "easy" },
  { word: "Stalagmite", category: "Nature", difficulty: "medium" },
  { word: "Seagull", category: "Nature", difficulty: "easy" },
  { word: "Pufferfish", category: "Nature", difficulty: "easy" },
  { word: "Praying Mantis", category: "Nature", difficulty: "easy" },
  { word: "Sloth", category: "Nature", difficulty: "easy" },
  { word: "Woodpecker", category: "Nature", difficulty: "easy" },
  { word: "Porcupine", category: "Nature", difficulty: "easy" },
  { word: "Skunk", category: "Nature", difficulty: "easy" },
  { word: "Lemur", category: "Nature", difficulty: "easy" },
  { word: "Beaver", category: "Nature", difficulty: "easy" },
  { word: "Meerkat", category: "Nature", difficulty: "easy" },
  { word: "Walrus", category: "Nature", difficulty: "easy" },
  { word: "Armadillo", category: "Nature", difficulty: "easy" },
  { word: "Raccoon", category: "Nature", difficulty: "easy" },
  { word: "Peacock", category: "Nature", difficulty: "easy" },
  { word: "Ostrich", category: "Nature", difficulty: "easy" },
  { word: "Seahorse", category: "Nature", difficulty: "easy" },
  { word: "Hammerhead Shark", category: "Nature", difficulty: "easy" },
  { word: "Stingray", category: "Nature", difficulty: "easy" },
  { word: "Electric Eel", category: "Nature", difficulty: "easy" },
  { word: "Barnacle", category: "Nature", difficulty: "medium" },
  { word: "Venus Flytrap", category: "Nature", difficulty: "easy" },
  { word: "Baobab Tree", category: "Nature", difficulty: "medium" },
  { word: "Bonsai Tree", category: "Nature", difficulty: "easy" },
  { word: "Poison Ivy", category: "Nature", difficulty: "easy" },
  { word: "Tumbleweed", category: "Nature", difficulty: "easy" },
  { word: "Mudslide", category: "Nature", difficulty: "easy" },
  { word: "Whirlpool", category: "Nature", difficulty: "easy" },
  { word: "Sandstorm", category: "Nature", difficulty: "easy" },
  { word: "Hailstorm", category: "Nature", difficulty: "easy" },
  { word: "Northern Lights", category: "Nature", difficulty: "easy" },
  { word: "Meteor Shower", category: "Nature", difficulty: "easy" },
  { word: "Koala", category: "Nature", difficulty: "easy" },
  { word: "Hummingbird", category: "Nature", difficulty: "easy" },
  { word: "Pelican", category: "Nature", difficulty: "easy" },
  { word: "Kingfisher", category: "Nature", difficulty: "easy" },
  { word: "Antelope", category: "Nature", difficulty: "easy" },
  { word: "Grizzly Bear", category: "Nature", difficulty: "easy" },
  { word: "Cheetah", category: "Nature", difficulty: "easy" },
  { word: "Gazelle", category: "Nature", difficulty: "easy" },
  { word: "Hyena", category: "Nature", difficulty: "easy" },
  { word: "Baboon", category: "Nature", difficulty: "easy" },
  { word: "Tarantula", category: "Nature", difficulty: "easy" },
  { word: "Centipede", category: "Nature", difficulty: "easy" },
  { word: "Sea Urchin", category: "Nature", difficulty: "easy" },
  { word: "Clam", category: "Nature", difficulty: "easy" },
  { word: "Tsunami", category: "Nature", difficulty: "easy" },
  { word: "Fern", category: "Nature", difficulty: "easy" },
  { word: "Sea Anemone", category: "Nature", difficulty: "medium" },
  { word: "Fire Ant", category: "Nature", difficulty: "easy" },
  { word: "Cicada", category: "Nature", difficulty: "easy" },
  { word: "Gila Monster", category: "Nature", difficulty: "hard" },
  { word: "Komodo Dragon", category: "Nature", difficulty: "easy" },
  { word: "Python", category: "Nature", difficulty: "easy" },
  { word: "Anaconda", category: "Nature", difficulty: "easy" },
  { word: "Cobra", category: "Nature", difficulty: "easy" },
  { word: "Rattlesnake", category: "Nature", difficulty: "easy" },
  { word: "Gecko", category: "Nature", difficulty: "easy" },
  { word: "Salamander", category: "Nature", difficulty: "medium" },
  { word: "Axolotl", category: "Nature", difficulty: "medium" },
  { word: "Barracuda", category: "Nature", difficulty: "medium" },
  { word: "Swordfish", category: "Nature", difficulty: "easy" },
  { word: "Manta Ray", category: "Nature", difficulty: "easy" },
  { word: "Sea Otter", category: "Nature", difficulty: "easy" },
  { word: "Polar Bear", category: "Nature", difficulty: "easy" },
  { word: "Red Panda", category: "Nature", difficulty: "easy" },
  { word: "Giant Panda", category: "Nature", difficulty: "easy" },
  { word: "Coyote", category: "Nature", difficulty: "easy" },
  { word: "Dingo", category: "Nature", difficulty: "easy" },
  { word: "Queen Victoria", category: "Person", difficulty: "easy" },
  { word: "Marilyn Monroe", category: "Person", difficulty: "easy" },
  { word: "David Beckham", category: "Person", difficulty: "easy" },
  { word: "Michael Jackson", category: "Person", difficulty: "easy" },
  { word: "Mother Teresa", category: "Person", difficulty: "easy" },
  { word: "Barack Obama", category: "Person", difficulty: "easy" },
  { word: "Charlie Chaplin", category: "Person", difficulty: "easy" },
  { word: "Walt Disney", category: "Person", difficulty: "easy" },
  { word: "Sherlock Holmes", category: "Person", difficulty: "easy" },
  { word: "Robin Hood", category: "Person", difficulty: "easy" },
  { word: "Santa Claus", category: "Person", difficulty: "easy" },
  { word: "Harry Potter", category: "Person", difficulty: "easy" },
  { word: "Blackbeard", category: "Person", difficulty: "easy" },
  { word: "Hercules", category: "Person", difficulty: "easy" },
  { word: "Frankenstein", category: "Person", difficulty: "easy" },
  { word: "Count Dracula", category: "Person", difficulty: "easy" },
  { word: "James Bond", category: "Person", difficulty: "easy" },
  { word: "Elvis Presley", category: "Person", difficulty: "easy" },
  { word: "Mahatma Gandhi", category: "Person", difficulty: "easy" },
  { word: "Usain Bolt", category: "Person", difficulty: "easy" },
  { word: "Serena Williams", category: "Person", difficulty: "easy" },
  { word: "Beyonce", category: "Person", difficulty: "easy" },
  { word: "Blacksmith", category: "Person", difficulty: "medium" },
  { word: "Detective", category: "Person", difficulty: "easy" },
  { word: "Referee", category: "Person", difficulty: "easy" },
  { word: "Optician", category: "Person", difficulty: "easy" },
  { word: "Conductor", category: "Person", difficulty: "easy" },
  { word: "Auctioneer", category: "Person", difficulty: "medium" },
  { word: "Archaeologist", category: "Person", difficulty: "medium" },
  { word: "Magician", category: "Person", difficulty: "easy" },
  { word: "Puppeteer", category: "Person", difficulty: "medium" },
  { word: "Deep Sea Diver", category: "Person", difficulty: "medium" },
  { word: "Stuntman", category: "Person", difficulty: "easy" },
  { word: "Ventriloquist", category: "Person", difficulty: "medium" },
  { word: "Sommelier", category: "Person", difficulty: "hard" },
  { word: "Chimney Sweep", category: "Person", difficulty: "medium" },
  { word: "Butcher", category: "Person", difficulty: "easy" },
  { word: "Cobbler", category: "Person", difficulty: "medium" },
  { word: "Sailor", category: "Person", difficulty: "easy" },
  { word: "Judge", category: "Person", difficulty: "easy" },
  { word: "Paramedic", category: "Person", difficulty: "easy" },
  { word: "Sculptor", category: "Person", difficulty: "easy" },
  { word: "Secret Agent", category: "Person", difficulty: "easy" },
  { word: "Queen Elizabeth II", category: "Person", difficulty: "easy" },
  { word: "Martin Luther King Jr.", category: "Person", difficulty: "easy" },
  { word: "Neil Armstrong", category: "Person", difficulty: "easy" },
  { word: "Princess Diana", category: "Person", difficulty: "easy" },
  { word: "Cristiano Ronaldo", category: "Person", difficulty: "easy" },
  { word: "Lionel Messi", category: "Person", difficulty: "easy" },
  { word: "Bob Marley", category: "Person", difficulty: "easy" },
  { word: "Christopher Columbus", category: "Person", difficulty: "easy" },
  { word: "Steve Jobs", category: "Person", difficulty: "easy" },
  { word: "Bill Gates", category: "Person", difficulty: "easy" },
  { word: "Jane Goodall", category: "Person", difficulty: "easy" },
  { word: "Alexander Hamilton", category: "Person", difficulty: "easy" },
  { word: "George Washington", category: "Person", difficulty: "easy" },
  { word: "Benjamin Franklin", category: "Person", difficulty: "easy" },
  { word: "Franklin D. Roosevelt", category: "Person", difficulty: "easy" },
  { word: "Theodore Roosevelt", category: "Person", difficulty: "easy" },
  { word: "Margaret Thatcher", category: "Person", difficulty: "easy" },
  { word: "Queen Elizabeth I", category: "Person", difficulty: "easy" },
  { word: "Joan of Arc", category: "Person", difficulty: "easy" },
  { word: "Florence Nightingale", category: "Person", difficulty: "easy" },
  { word: "Helen Keller", category: "Person", difficulty: "easy" },
  { word: "Hiccuping", category: "Action", difficulty: "easy" },
  { word: "Moonwalking", category: "Action", difficulty: "easy" },
  { word: "Somersaulting", category: "Action", difficulty: "easy" },
  { word: "Yodeling", category: "Action", difficulty: "medium" },
  { word: "Ice Skating", category: "Action", difficulty: "easy" },
  { word: "Shuffling Cards", category: "Action", difficulty: "easy" },
  { word: "Sleepwalking", category: "Action", difficulty: "easy" },
  { word: "Whistling", category: "Action", difficulty: "easy" },
  { word: "Arm Wrestling", category: "Action", difficulty: "easy" },
  { word: "Milking a Cow", category: "Action", difficulty: "easy" },
  { word: "Flipping a Pancake", category: "Action", difficulty: "easy" },
  { word: "Playing Chess", category: "Action", difficulty: "easy" },
  { word: "Hula Hooping", category: "Action", difficulty: "easy" },
  { word: "Sunbathing", category: "Action", difficulty: "easy" },
  { word: "Ironing a Shirt", category: "Action", difficulty: "easy" },
  { word: "Bowling", category: "Action", difficulty: "easy" },
  { word: "Peeling a Banana", category: "Action", difficulty: "easy" },
  { word: "Blowing a Bubble", category: "Action", difficulty: "easy" },
  { word: "Building a Sandcastle", category: "Action", difficulty: "easy" },
  { word: "Riding a Unicycle", category: "Action", difficulty: "medium" },
  { word: "Tying a Tie", category: "Action", difficulty: "easy" },
  { word: "Doing a Cartwheel", category: "Action", difficulty: "easy" },
  { word: "Playing Bagpipes", category: "Action", difficulty: "medium" },
  { word: "Walking on Eggshells", category: "Action", difficulty: "medium" },
  { word: "Shadowboxing", category: "Action", difficulty: "easy" },
  { word: "Shivering", category: "Action", difficulty: "easy" },
  { word: "Cracking Knuckles", category: "Action", difficulty: "easy" },
  { word: "Plucking Eyebrows", category: "Action", difficulty: "easy" },
  { word: "Walking on Stilts", category: "Action", difficulty: "medium" },
  { word: "Chewing Gum", category: "Action", difficulty: "easy" },
  { word: "Diving into a Pool", category: "Action", difficulty: "easy" },
  { word: "Skipping Rope", category: "Action", difficulty: "easy" },
  { word: "Bouncing a Ball", category: "Action", difficulty: "easy" },
  { word: "Slicing Bread", category: "Action", difficulty: "easy" },
  { word: "Threading a Needle", category: "Action", difficulty: "easy" },
  { word: "Catching a Frisbee", category: "Action", difficulty: "easy" },
  { word: "Chopping Wood", category: "Action", difficulty: "easy" },
  { word: "Flying a Kite", category: "Action", difficulty: "easy" },
  { word: "Playing Marbles", category: "Action", difficulty: "easy" },
  { word: "Blowing Out Candles", category: "Action", difficulty: "easy" },
  { word: "Tossing a Coin", category: "Action", difficulty: "easy" },
  { word: "Wrapping a Present", category: "Action", difficulty: "easy" },
  { word: "Climbing a Rope", category: "Action", difficulty: "easy" },
  { word: "Peeling an Orange", category: "Action", difficulty: "easy" },
  { word: "Buttering Toast", category: "Action", difficulty: "easy" },
  { word: "Tuning a Guitar", category: "Action", difficulty: "easy" },
  { word: "Brushing Hair", category: "Action", difficulty: "easy" },
  { word: "Playing Hopscotch", category: "Action", difficulty: "easy" },
  { word: "Digging a Hole", category: "Action", difficulty: "easy" },
  { word: "Roasting Marshmallows", category: "Action", difficulty: "easy" },
  { word: "Blowing a Kiss", category: "Action", difficulty: "easy" },
  { word: "Popping Bubble Wrap", category: "Action", difficulty: "easy" },
  { word: "Playing Tag", category: "Action", difficulty: "easy" },
  { word: "Building a Campfire", category: "Action", difficulty: "easy" },
  { word: "Snapping Fingers", category: "Action", difficulty: "easy" },
  { word: "Winking", category: "Action", difficulty: "easy" },
  { word: "Breakdancing", category: "Action", difficulty: "easy" },
  { word: "Tap Dancing", category: "Action", difficulty: "easy" },
  { word: "Salsa Dancing", category: "Action", difficulty: "easy" },
  { word: "Hula Dancing", category: "Action", difficulty: "easy" },
  { word: "Sumo Wrestling", category: "Action", difficulty: "easy" },
  { word: "Fencing", category: "Action", difficulty: "easy" },
  { word: "Archery", category: "Action", difficulty: "easy" },
  { word: "Whitewater Rafting", category: "Action", difficulty: "easy" },
  { word: "Paddleboarding", category: "Action", difficulty: "easy" },
  { word: "Kayaking", category: "Action", difficulty: "easy" },
  { word: "Canoeing", category: "Action", difficulty: "easy" },
  { word: "Windsurfing", category: "Action", difficulty: "medium" },
  { word: "Kitesurfing", category: "Action", difficulty: "medium" },
  { word: "Water Skiing", category: "Action", difficulty: "easy" },
  { word: "Wakeboarding", category: "Action", difficulty: "easy" },
  { word: "Snowboarding", category: "Action", difficulty: "easy" },
  { word: "Bobsledding", category: "Action", difficulty: "medium" },
  { word: "Curling", category: "Action", difficulty: "medium" },
  { word: "Rollerblading", category: "Action", difficulty: "easy" },
  { word: "Amazon Rainforest", category: "World", difficulty: "easy" },
  { word: "Pyramids of Giza", category: "World", difficulty: "easy" },
  { word: "Buckingham Palace", category: "World", difficulty: "easy" },
  { word: "Hollywood Sign", category: "World", difficulty: "easy" },
  { word: "North Pole", category: "World", difficulty: "easy" },
  { word: "Madagascar", category: "World", difficulty: "easy" },
  { word: "Chernobyl", category: "World", difficulty: "medium" },
  { word: "Times Square", category: "World", difficulty: "easy" },
  { word: "Pompeii", category: "World", difficulty: "medium" },
  { word: "Victoria Falls", category: "World", difficulty: "easy" },
  { word: "Alcatraz", category: "World", difficulty: "medium" },
  { word: "Brandenburg Gate", category: "World", difficulty: "medium" },
  { word: "Las Vegas Strip", category: "World", difficulty: "easy" },
  { word: "Mount Olympus", category: "World", difficulty: "medium" },
  { word: "Tower of London", category: "World", difficulty: "easy" },
  { word: "Sistine Chapel", category: "World", difficulty: "medium" },
  { word: "Great Sphinx", category: "World", difficulty: "easy" },
  { word: "Christ the Redeemer", category: "World", difficulty: "easy" },
  { word: "Burj Khalifa", category: "World", difficulty: "easy" },
  { word: "Saint Basil Cathedral", category: "World", difficulty: "medium" },
  { word: "Windsor Castle", category: "World", difficulty: "easy" },
  { word: "Table Mountain", category: "World", difficulty: "medium" },
  { word: "Giant Causeway", category: "World", difficulty: "hard" },
  { word: "Mont Saint-Michel", category: "World", difficulty: "hard" },
  { word: "Blue Lagoon", category: "World", difficulty: "medium" },
  { word: "Matterhorn", category: "World", difficulty: "hard" },
  { word: "Serengeti National Park", category: "World", difficulty: "easy" },
  { word: "Kruger National Park", category: "World", difficulty: "medium" },
  { word: "Yosemite National Park", category: "World", difficulty: "easy" },
  { word: "Death Valley", category: "World", difficulty: "easy" },
  { word: "Everglades", category: "World", difficulty: "easy" },
  { word: "Mont Blanc", category: "World", difficulty: "medium" },
  { word: "Mount Vesuvius", category: "World", difficulty: "easy" },
  { word: "Krakatoa", category: "World", difficulty: "medium" },
  { word: "Mount Etna", category: "World", difficulty: "medium" },
  { word: "Mount St. Helens", category: "World", difficulty: "medium" },
  { word: "Yangtze River", category: "World", difficulty: "medium" },
  { word: "Mississippi River", category: "World", difficulty: "easy" },
  { word: "Danube River", category: "World", difficulty: "medium" },
  { word: "Thames River", category: "World", difficulty: "easy" },
  { word: "Seine River", category: "World", difficulty: "easy" },
  { word: "Rhine River", category: "World", difficulty: "medium" },
  { word: "Ganges River", category: "World", difficulty: "easy" },
  { word: "April Fools Day", category: "Random", difficulty: "easy" },
  { word: "Friday the 13th", category: "Random", difficulty: "easy" },
  { word: "Rush Hour", category: "Random", difficulty: "easy" },
  { word: "Blind Date", category: "Random", difficulty: "easy" },
  { word: "Leap Year", category: "Random", difficulty: "easy" },
  { word: "Black Friday", category: "Random", difficulty: "easy" },
  { word: "Chinese New Year", category: "Random", difficulty: "easy" },
  { word: "First Kiss", category: "Random", difficulty: "easy" },
  { word: "Midlife Crisis", category: "Random", difficulty: "easy" },
  { word: "Silent Disco", category: "Random", difficulty: "easy" },
  { word: "Speed Dating", category: "Random", difficulty: "easy" },
  { word: "Karaoke Night", category: "Random", difficulty: "easy" },
  { word: "Red Carpet", category: "Random", difficulty: "easy" },
  { word: "Food Fight", category: "Random", difficulty: "easy" },
  { word: "Secret Santa", category: "Random", difficulty: "easy" },
  { word: "Honeymoon", category: "Random", difficulty: "easy" },
  { word: "Bachelor Party", category: "Random", difficulty: "easy" },
  { word: "Road Trip", category: "Random", difficulty: "easy" },
  { word: "Flash Mob", category: "Random", difficulty: "easy" },
  { word: "Baby Shower", category: "Random", difficulty: "easy" },
  { word: "Housewarming", category: "Random", difficulty: "easy" },
  { word: "Groundhog Day", category: "Random", difficulty: "easy" },
  { word: "Prom Night", category: "Random", difficulty: "easy" },
  { word: "Pop Quiz", category: "Random", difficulty: "easy" },
  { word: "Carpool", category: "Random", difficulty: "easy" },
  { word: "Garage Sale", category: "Random", difficulty: "easy" },
  { word: "Pillow Fight", category: "Random", difficulty: "easy" },
  { word: "Tailgating", category: "Random", difficulty: "easy" },
  { word: "Double Date", category: "Random", difficulty: "easy" },
  { word: "Potluck", category: "Random", difficulty: "easy" },
  { word: "Midnight Snack", category: "Random", difficulty: "easy" },
  { word: "Sleepover", category: "Random", difficulty: "easy" },
  { word: "Trick or Treat", category: "Random", difficulty: "easy" },
  { word: "New Years Resolution", category: "Random", difficulty: "easy" },
  { word: "Standing Ovation", category: "Random", difficulty: "easy" },
  { word: "Fist Bump", category: "Random", difficulty: "easy" },
  { word: "Poker Face", category: "Random", difficulty: "easy" },
  { word: "Bucket List", category: "Random", difficulty: "easy" },
  { word: "Brain Freeze", category: "Random", difficulty: "easy" },
  { word: "Deja Vu", category: "Random", difficulty: "easy" },
  { word: "Lucky Charm", category: "Random", difficulty: "easy" },
  { word: "Power Outage", category: "Random", difficulty: "easy" },
  { word: "Goosebumps", category: "Random", difficulty: "easy" },
  { word: "Golden Ticket", category: "Random", difficulty: "easy" },
  { word: "Murphys Law", category: "Random", difficulty: "medium" },
  { word: "Red Herring", category: "Random", difficulty: "medium" },
  { word: "White Lie", category: "Random", difficulty: "easy" },
  { word: "Silver Lining", category: "Random", difficulty: "easy" },
  { word: "Jackpot", category: "Random", difficulty: "easy" },
  { word: "Scavenger Hunt", category: "Random", difficulty: "easy" },
  { word: "Time Capsule", category: "Random", difficulty: "easy" },
  { word: "Talent Show", category: "Random", difficulty: "easy" },
  { word: "Spelling Bee", category: "Random", difficulty: "easy" },
  { word: "Masquerade Ball", category: "Random", difficulty: "medium" },
  { word: "Block Party", category: "Random", difficulty: "easy" },
  { word: "House of Cards", category: "Random", difficulty: "easy" },
  { word: "Black Hole", category: "Random", difficulty: "easy" },
  { word: "Solar Flare", category: "Random", difficulty: "medium" },
  { word: "Area 51", category: "Random", difficulty: "easy" },
  { word: "Roswell Incident", category: "Random", difficulty: "medium" },
  { word: "Trojan Horse", category: "Random", difficulty: "easy" },
  { word: "Achilles Heel", category: "Random", difficulty: "easy" },
  { word: "Pandoras Box", category: "Random", difficulty: "easy" },
  { word: "Midas Touch", category: "Random", difficulty: "easy" },
  { word: "Holy Grail", category: "Random", difficulty: "easy" },
  { word: "Fountain of Youth", category: "Random", difficulty: "easy" },
  { word: "El Dorado", category: "Random", difficulty: "easy" },
  { word: "Atlantis", category: "Random", difficulty: "easy" },
];

function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

export function buildDeck(
  categories?: GameCategory[],
  difficulty: GameDifficulty = "mixed",
  count = 60,
  excludeWords: string[] = []
): GameWord[] {
  const safeCategories = Array.isArray(categories) && categories.length > 0 ? categories : GAME_CATEGORIES;
  const safeDiff = difficulty || "mixed";
  const safeExclude = Array.isArray(excludeWords) ? excludeWords : [];

  // Pass 1: exact category, difficulty, excluding used words
  let categoryPool = GAME_WORDS.filter((w) => safeCategories.includes(w.category));
  if (categoryPool.length === 0) categoryPool = GAME_WORDS;

  let filtered = categoryPool;
  if (safeDiff === "easy") {
    filtered = categoryPool.filter((w) => w.difficulty === "easy");
  } else if (safeDiff === "hard") {
    filtered = categoryPool.filter((w) => w.difficulty !== "easy");
  }
  if (filtered.length === 0) filtered = categoryPool;

  let finalPool = filtered;
  if (safeExclude.length > 0) {
    const withoutExcluded = filtered.filter((w) => !safeExclude.includes(w.word));
    // If enough words remain (at least 10), use withoutExcluded; otherwise recycle used words
    if (withoutExcluded.length >= 10) {
      finalPool = withoutExcluded;
    }
  }

  // Fallback 1: if finalPool is empty, relax difficulty constraint for these categories
  if (finalPool.length === 0) {
    finalPool = categoryPool.filter((w) => !safeExclude.includes(w.word));
    if (finalPool.length < 5) finalPool = categoryPool;
  }

  // Fallback 2: if still empty, fall back to entire GAME_WORDS
  if (finalPool.length === 0) {
    finalPool = GAME_WORDS;
  }

  return shuffle(finalPool).slice(0, count);
}
