"use client";

import { useEffect, useState, useRef } from "react";
import { useRouter } from "next/navigation";
import ReactFlow, {
  Background, Controls, MiniMap,
  type Node, type Edge, type NodeTypes,
  Handle, Position, MarkerType,
  useNodesState, useEdgesState,
} from "reactflow";
import "reactflow/dist/style.css";
import { motion, AnimatePresence } from "framer-motion";
import { Search, X, Star, BookOpen, Calendar, Mic, Volume2 } from "lucide-react";
import { useAppStore, type CompletedSession } from "@/store/useAppStore";
import { CATEGORY_COLORS, CATEGORY_ICONS, TOPIC_BANK, type Topic } from "@/lib/topics";
import { relativeDate, cn } from "@/lib/utils";

// ─── Utility: Blob to Base64 ────────────────────────────────────────────────
function blobToBase64(blob: Blob): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(reader.result as string);
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
}

// ─── Similar Topics Recommendation Engine ─────────────────────────────────────
function getSimilarTopics(currentTopicId: string, category: string, currentTags: string[]) {
  const pool = TOPIC_BANK.filter((t) => t.id !== currentTopicId);
  const scored = pool.map((t) => {
    let score = 0;
    if (t.category === category) score += 10;
    if (t.tags && currentTags) {
      const intersect = t.tags.filter((tag) => currentTags.includes(tag));
      score += intersect.length * 3;
    }
    return { topic: t, score };
  });

  return scored
    .filter((item) => item.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, 3)
    .map((item) => item.topic);
}

// ─── Topic Generation Templates ──────────────────────────────────────────────
const GENERATOR_TEMPLATES: Record<string, string[]> = {
  "Artificial Intelligence": [
    "How will the alignment problem evolve as AI models reach superhuman intelligence?",
    "Can consciousness arise from neural structures, or is it unique to biological brains?",
    "Should code generated by AI be open-source by default? Defend your view."
  ],
  "Technology": [
    "What are the societal implications of quantum computing on modern cryptography?",
    "How will brain-computer interfaces redefine user experience in the next decade?",
    "Is decentralization the answer to the monopolization of web services?"
  ],
  "Software Engineering": [
    "Compare the maintenance costs of microservices versus monolithic systems.",
    "How does the choice of programming paradigm affect long-term codebase health?",
    "Should developers be held legally liable for security bugs in open source?"
  ],
  "Finance": [
    "Explain how high-frequency trading affects market volatility and price discovery.",
    "Will CBDCs (Central Bank Digital Currencies) replace commercial banks? Explain.",
    "How do negative interest rates invert traditional financial incentives?"
  ],
  "Economics": [
    "Is universal basic income (UBI) a viable solution to automation-led job displacement?",
    "How does game theory explain international climate policy cooperation failures?",
    "Explain the tragedy of the commons through a modern environmental lens."
  ],
  "Psychology": [
    "How does digital cognitive overload alter attention spans in children?",
    "Can neuroplasticity be actively accelerated in adults? Detail the mechanisms.",
    "Why do group dynamics frequently lead to extreme risk-taking behaviors (groupthink)?"
  ],
  "Business": [
    "Why do network effects create winner-take-all dynamics in platform markets?",
    "How should a legacy enterprise restructure to defend against modular startup competitors?",
    "Is shareholder value maximization still a viable primary corporate objective?"
  ],
  "Science": [
    "Explain how gene drive technology could eradicate malaria vectors, and the ethical risks.",
    "What is the physical significance of the cosmic microwave background radiation?",
    "How does cellular senescence contribute to aging, and can it be reversed?"
  ],
  "Philosophy": [
    "Does free will exist in a deterministic universe? Argue your position.",
    "How does existential nihilism differ from optimistic nihilism?",
    "What is the ethical status of uploaded digital minds?"
  ],
  "Startups": [
    "Is bootstrapping superior to venture capital for building sustainable tech companies?",
    "How do you execute a pivot when your initial product-market fit fails?",
    "Explain the 'cold start problem' for dual-sided marketplace startups."
  ]
};

// ─── Custom node ─────────────────────────────────────────────────────────────
function TopicNode({ data }: { data: { session: CompletedSession; onClick: () => void } }) {
  const { session } = data;
  const color = CATEGORY_COLORS[session.category] ?? "var(--olive)";
  const confidence = session.ratings.confidence / 5;
  const size = 26 + confidence * 18;

  return (
    <div
      onClick={data.onClick}
      className="cursor-pointer group relative"
      style={{ width: size * 2, height: size * 2 }}
    >
      <Handle type="target" position={Position.Top} style={{ opacity: 0 }} />
      <div
        className="w-full h-full rounded-full flex items-center justify-center transition-all duration-200 group-hover:scale-110"
        style={{
          background: `radial-gradient(circle at 35% 35%, rgba(30, 34, 17, 0.95), rgba(18, 22, 11, 0.9))`,
          boxShadow: `0 0 16px ${color}35`,
          border: `2.5px solid ${color}`,
        }}
      >
        <span style={{ fontSize: Math.max(12, size * 0.45) }}>{CATEGORY_ICONS[session.category]}</span>
      </div>
      <Handle type="source" position={Position.Bottom} style={{ opacity: 0 }} />

      {/* Hover label */}
      <div className="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none z-10">
        <div className="rounded-lg px-2.5 py-1 text-xs whitespace-nowrap max-w-[200px] truncate surface-raised" style={{ color: "var(--text)" }}>
          {session.topicText}
        </div>
      </div>
    </div>
  );
}

const nodeTypes: NodeTypes = { topic: TopicNode };

// ─── Force-directed layout ────────────────────────────────────────────────────
function layoutNodes(sessions: CompletedSession[]): { nodes: Node[]; edges: Edge[] } {
  const categoryGroups: Record<string, CompletedSession[]> = {};
  sessions.forEach((s) => {
    if (!categoryGroups[s.category]) categoryGroups[s.category] = [];
    categoryGroups[s.category].push(s);
  });

  const cats = Object.keys(categoryGroups);
  const nodes: Node[] = [];
  const edges: Edge[] = [];
  const catAngles: Record<string, number> = {};
  cats.forEach((cat, i) => { catAngles[cat] = (2 * Math.PI * i) / cats.length; });

  sessions.forEach((session) => {
    const cat = session.category;
    const catSessions = categoryGroups[cat];
    const angle = catAngles[cat];
    const radius = 220 + catSessions.length * 18;
    const idx = catSessions.indexOf(session);
    const spread = (2 * Math.PI) / Math.max(catSessions.length, 1) * 0.35;
    const nodeAngle = angle + (idx - catSessions.length / 2) * spread;
    const jitter = () => (Math.random() - 0.5) * 30;

    const catColor = CATEGORY_COLORS[cat] ?? "var(--olive)";

    nodes.push({
      id: session.id,
      type: "topic",
      position: {
        x: 400 + Math.cos(nodeAngle) * radius + jitter(),
        y: 300 + Math.sin(nodeAngle) * radius + jitter(),
      },
      data: { session, onClick: () => {} },
    });

    // Connecting nodes in the same category
    if (idx > 0) {
      edges.push({
        id: `${catSessions[idx - 1].id}-${session.id}`,
        source: catSessions[idx - 1].id,
        target: session.id,
        style: {
          stroke: catColor,
          strokeWidth: 2,
          strokeDasharray: "6, 12",
          animation: "edgePulse 1.2s linear infinite",
          opacity: 0.6,
        },
        markerEnd: {
          type: MarkerType.ArrowClosed,
          color: catColor,
          width: 8,
          height: 8,
        },
      });
    }
  });

  // Connecting adjacent categories into a central ring backbone
  for (let i = 0; i < cats.length; i++) {
    const nextCat = cats[(i + 1) % cats.length];
    const currentFirst = categoryGroups[cats[i]][0];
    const nextFirst = categoryGroups[nextCat][0];
    if (currentFirst && nextFirst) {
      edges.push({
        id: `inter-${currentFirst.id}-${nextFirst.id}`,
        source: currentFirst.id,
        target: nextFirst.id,
        style: {
          stroke: "var(--border-dim)",
          strokeWidth: 1.2,
          strokeDasharray: "4, 10",
          animation: "edgePulse 2s linear infinite",
          opacity: 0.25,
        },
      });
    }
  }

  return { nodes, edges };
}

// ─── Detail panel ─────────────────────────────────────────────────────────────
function NodeDetail({ session, onClose }: { session: CompletedSession; onClose: () => void }) {
  const router = useRouter();
  const { settings, toggleFavoriteTopic, updateSessionAudio, addCustomTopic, startSession } = useAppStore();
  
  // Re-recording states
  const [isRecordingNew, setIsRecordingNew] = useState(false);
  const [recordingSeconds, setRecordingSeconds] = useState(0);
  const [stream, setStream] = useState<MediaStream | null>(null);
  const [mediaRecorder, setMediaRecorder] = useState<MediaRecorder | null>(null);
  const chunksRef = useRef<Blob[]>([]);
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  // Recommendations states
  const similar = getSimilarTopics(session.topicId, session.category, session.tags || []);
  const [customGenUsed, setCustomGenUsed] = useState(false);
  const [customTopicList, setCustomTopicList] = useState<Topic[]>([]);

  const isFav = settings.favoriteTopics?.includes(session.topicId) || false;

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      if (timerRef.current) clearInterval(timerRef.current);
    };
  }, []);

  async function startMiniRecording() {
    try {
      const s = await navigator.mediaDevices.getUserMedia({ audio: true });
      setStream(s);
      const mimeType = MediaRecorder.isTypeSupported("audio/webm") ? "audio/webm" : "audio/mp4";
      const mr = new MediaRecorder(s, { mimeType });
      setMediaRecorder(mr);
      chunksRef.current = [];

      mr.ondataavailable = (e) => {
        if (e.data.size > 0) chunksRef.current.push(e.data);
      };

      mr.onstop = async () => {
        const blob = new Blob(chunksRef.current, { type: mimeType });
        try {
          const base64 = await blobToBase64(blob);
          updateSessionAudio(session.id, base64, recordingSeconds || 1);
        } catch (err) {
          console.error("Failed to convert re-recording to base64", err);
        }
        s.getTracks().forEach((track) => track.stop());
      };

      mr.start(200);
      setIsRecordingNew(true);
      setRecordingSeconds(0);

      let elapsed = 0;
      timerRef.current = setInterval(() => {
        elapsed += 1;
        setRecordingSeconds(elapsed);
        if (elapsed >= 60) {
          stopMiniRecording(mr);
        }
      }, 1000);
    } catch (err) {
      console.error("Failed to access mic for mini recording", err);
    }
  }

  function stopMiniRecording(mrActive?: MediaRecorder | null) {
    if (timerRef.current) clearInterval(timerRef.current);
    const activeMr = mrActive || mediaRecorder;
    if (activeMr && activeMr.state !== "inactive") {
      activeMr.stop();
    }
    setIsRecordingNew(false);
  }

  function cancelMiniRecording() {
    if (timerRef.current) clearInterval(timerRef.current);
    if (mediaRecorder && mediaRecorder.state !== "inactive") {
      mediaRecorder.ondataavailable = null;
      mediaRecorder.onstop = null;
      mediaRecorder.stop();
    }
    if (stream) {
      stream.getTracks().forEach((t) => t.stop());
    }
    setIsRecordingNew(false);
    setRecordingSeconds(0);
  }

  function generateCustomTopic() {
    const list = GENERATOR_TEMPLATES[session.category] || [
      `What are the most challenging trade-offs when implementing new methodologies in ${session.category}?`,
      `Explain the long-term impact of regulatory disruption on key players in ${session.category}.`
    ];
    const pickedText = list[Math.floor(Math.random() * list.length)];
    const generated: Topic = {
      id: `gen-${Date.now()}`,
      text: pickedText,
      category: session.category,
      difficulty: "Scholar",
      tags: ["generative", ...(session.tags || [])]
    };
    setCustomTopicList((prev) => [...prev, generated]);
    setCustomGenUsed(true);
  }

  function startSessionOn(topic: Topic) {
    addCustomTopic(topic);
    const activeId = startSession(topic, settings.researchMin || 15);
    router.push(`/session/${activeId}`);
  }

  return (
    <motion.div
      initial={{ x: 320, opacity: 0 }}
      animate={{ x: 0, opacity: 1 }}
      exit={{ x: 320, opacity: 0 }}
      transition={{ type: "spring", stiffness: 300, damping: 30 }}
      className="absolute right-0 top-0 h-full w-85 overflow-y-auto z-20 p-6 flex flex-col gap-5 border-l"
      style={{ backgroundColor: "var(--bg-card)", borderColor: "var(--border)" }}
    >
      {/* Detail header */}
      <div className="flex items-start justify-between">
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-lg flex items-center justify-center text-base border" style={{ background: "var(--bg-input)", borderColor: "var(--border-dim)" }}>
            {CATEGORY_ICONS[session.category]}
          </div>
          <div>
            <div className="text-xs uppercase tracking-wider" style={{ color: "var(--text-mute)" }}>{session.category}</div>
            <div className="text-xs font-semibold uppercase tracking-widest font-mono text-[var(--olive-text)]">{session.difficulty}</div>
          </div>
        </div>
        <div className="flex items-center gap-1.5">
          {/* Favorite Toggle Star */}
          <button
            onClick={() => toggleFavoriteTopic(session.topicId)}
            title={isFav ? "Remove from Favorites" : "Add to Favorites"}
            className={cn(
              "p-1.5 rounded-lg border transition-all",
              isFav ? "border-yellow-500/20 bg-yellow-500/5" : "border-[var(--border-dim)] hover:bg-[var(--bg-input)]"
            )}
          >
            <Star
              size={13}
              className={cn("transition-colors", isFav ? "fill-yellow-500 text-yellow-500" : "text-[var(--text-mute)]")}
            />
          </button>
          <button onClick={onClose} className="text-[var(--text-mute)] hover:text-[var(--text)] p-1 transition-colors">
            <X size={14} />
          </button>
        </div>
      </div>

      <p className="font-space font-bold leading-snug text-sm text-display" style={{ color: "var(--text)", fontSize: "1.1rem" }}>{session.topicText}</p>

      <div className="flex items-center gap-1.5 text-xs font-mono" style={{ color: "var(--text-mute)" }}>
        <Calendar size={11} /> {relativeDate(session.date)} · {session.date}
      </div>

      {/* Ratings */}
      <div className="rounded-xl p-4 surface">
        <div className="text-label mb-3">Session assessment</div>
        <div className="space-y-2">
          {[
            { label: "Confidence", value: session.ratings.confidence },
            { label: "Understanding", value: session.ratings.understanding },
            { label: "Communication", value: session.ratings.communication },
          ].map((r) => (
            <div key={r.label} className="flex items-center justify-between">
              <span className="text-xs" style={{ color: "var(--text-dim)" }}>{r.label}</span>
              <div className="flex gap-0.5">
                {[1,2,3,4,5].map((i) => (
                  <Star key={i} size={10} className="fill-current" style={{ color: i <= r.value ? "var(--gold)" : "var(--text-mute)", opacity: i <= r.value ? 1 : 0.15 }} />
                ))}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-2 gap-2">
        <div className="rounded-xl p-3 text-center surface">
          <div className="font-mono font-semibold" style={{ color: "var(--text)", fontSize: "1.1rem" }}>{session.researchMinutes}m</div>
          <div className="text-[10px] flex items-center justify-center gap-1 mt-1" style={{ color: "var(--text-dim)" }}>
            <BookOpen size={9} /> Research
          </div>
        </div>
        <div className="rounded-xl p-3 text-center surface">
          <div className="font-mono font-semibold" style={{ color: "var(--text)", fontSize: "1.1rem" }}>{session.speakingSeconds}s</div>
          <div className="text-[10px] flex items-center justify-center gap-1 mt-1" style={{ color: "var(--text-dim)" }}>
            <Mic size={9} /> Speaking
          </div>
        </div>
      </div>

      {/* Reflection */}
      {session.reflection.interesting && (
        <div className="space-y-2">
          <div className="text-label">Interesting takeaway</div>
          <div className="rounded-xl p-3 text-xs leading-relaxed" style={{ background: "var(--bg-input)", color: "var(--text-dim)", border: "1px solid var(--border-dim)" }}>
            {session.reflection.interesting}
          </div>
        </div>
      )}

      {/* Audio Playback & Re-Recording */}
      <div className="divider" />
      
      {session.audioBase64 ? (
        <div className="space-y-2">
          <div className="text-label flex items-center gap-1.5"><Volume2 size={11} /> Last Audio Attempt</div>
          <div className="rounded-xl p-3 bg-[var(--bg-input)] border border-[var(--border-dim)]">
            <audio controls src={session.audioBase64} className="w-full h-8" />
          </div>
        </div>
      ) : (
        <div className="space-y-2">
          <div className="text-label flex items-center gap-1.5"><Volume2 size={11} /> Last Audio Attempt</div>
          <div className="rounded-xl p-4 bg-[var(--bg-input)] border border-[var(--border-dim)] text-center text-xs text-[var(--text-mute)]">
            No audio recorded for this attempt.
          </div>
        </div>
      )}

      {/* Re-record new audio attempt */}
      <div className="rounded-xl p-4 surface">
        <div className="text-label mb-2 flex items-center gap-1.5">
          <Mic size={11} /> Practice speech again
        </div>
        {isRecordingNew ? (
          <div className="flex flex-col items-center gap-3 py-2">
            <div className="flex items-center gap-2 px-3 py-1 rounded-full border bg-[var(--red-bg)] border-[var(--red)]">
              <div className="w-1.5 h-1.5 rounded-full bg-red-500 animate-pulse" />
              <span className="text-[10px] text-red-500 font-bold uppercase tracking-wider">Recording: {recordingSeconds}s</span>
            </div>
            <div className="flex gap-2 w-full">
              <button onClick={cancelMiniRecording} className="btn-ghost flex-1 py-1 text-xs">Cancel</button>
              <button onClick={() => stopMiniRecording(null)} className="btn-terra flex-1 py-1 text-xs">Save</button>
            </div>
          </div>
        ) : (
          <button
            onClick={startMiniRecording}
            className="w-full btn-ghost py-2 text-xs flex items-center justify-center gap-1.5"
          >
            <Mic size={12} /> Start New Speech Attempt
          </button>
        )}
      </div>

      {/* Similar Topics */}
      <div className="divider" />
      
      <div className="space-y-3 pb-4">
        <div className="text-label flex items-center justify-between">
          <span>Explore similar topics</span>
          {!customGenUsed && (
            <button
              onClick={generateCustomTopic}
              className="text-[10px] font-bold text-[var(--terra)] hover:underline flex items-center gap-0.5"
            >
              ✨ Generate Related
            </button>
          )}
        </div>
        <div className="space-y-2">
          {similar.length === 0 && customTopicList.length === 0 && (
            <div className="text-xs text-[var(--text-mute)] bg-[var(--bg-input)]/50 p-3 rounded-lg text-center">
              No other topics in this bank. Try generating a related one above!
            </div>
          )}
          {[...similar, ...customTopicList].map((t) => (
            <div key={t.id} className="rounded-xl p-3 border border-[var(--border-dim)] bg-[var(--bg-card)] flex flex-col gap-2">
              <p className="text-xs font-semibold leading-normal" style={{ color: "var(--text)" }}>{t.text}</p>
              <button
                onClick={() => startSessionOn(t)}
                className="btn-terra py-1.5 px-3 text-[10px] rounded-lg font-bold self-start"
              >
                Start Challenge
              </button>
            </div>
          ))}
        </div>
      </div>

      <div className="mt-auto pt-4 border-t flex items-center justify-between text-xs" style={{ borderColor: "var(--border-dim)" }}>
        <span style={{ color: "var(--text-mute)" }}>XP reward</span>
        <span className="font-mono font-bold" style={{ color: "var(--gold)" }}>+{session.xpEarned} XP</span>
      </div>
    </motion.div>
  );
}

const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.04,
    }
  }
};

const cardVariants = {
  hidden: { opacity: 0, y: 15 },
  visible: {
    opacity: 1,
    y: 0,
    transition: {
      type: "spring",
      stiffness: 260,
      damping: 18
    }
  }
};

// ─── Main Constellation ───────────────────────────────────────────────────────
export default function ConstellationPage() {
  const { sessions } = useAppStore();
  const [nodes, setNodes, onNodesChange] = useNodesState([]);
  const [edges, setEdges, onEdgesChange] = useEdgesState([]);
  const [selectedSession, setSelectedSession] = useState<CompletedSession | null>(null);
  const [query, setQuery] = useState("");
  const [filterCat, setFilterCat] = useState("all");

  const filtered = sessions.filter((s) =>
    (filterCat === "all" || s.category === filterCat) &&
    (query === "" || s.topicText.toLowerCase().includes(query.toLowerCase()))
  );

  useEffect(() => {
    const { nodes: n, edges: e } = layoutNodes(filtered);
    const withHandlers = n.map((node) => ({
      ...node,
      data: {
        ...node.data,
        onClick: () => setSelectedSession(node.data.session as CompletedSession),
      },
    }));
    setNodes(withHandlers);
    setEdges(e);
  }, [filtered.length, filterCat, query]);

  // Keep selected session data fresh if updated
  const activeDetailSession = selectedSession
    ? sessions.find((s) => s.id === selectedSession.id) || selectedSession
    : null;

  const uniqueCats = [...new Set(sessions.map((s) => s.category))];

  return (
    <motion.div
      variants={containerVariants}
      initial="hidden"
      animate="visible"
      className="h-screen flex flex-col overflow-hidden"
    >
      <style dangerouslySetInnerHTML={{__html: `
        @keyframes edgePulse {
          to {
            stroke-dashoffset: -36;
          }
        }
      `}} />
      {/* Header */}
      <motion.div
        variants={cardVariants}
        className="px-8 py-5 flex items-start justify-between border-b"
        style={{ borderColor: "var(--border-dim)" }}
      >
        <div>
          <h1 className="font-space text-3xl font-bold mb-1 text-display" style={{ color: "var(--text)" }}>Knowledge Constellation</h1>
          <p style={{ color: "var(--text-dim)" }} className="text-xs">{sessions.length} topics mastered · {uniqueCats.length} categories explored</p>
        </div>
        <div className="flex items-center gap-3">
          <div className="relative">
            <Search size={13} className="absolute left-3 top-1/2 -translate-y-1/2" style={{ color: "var(--text-mute)" }} />
            <input
              placeholder="Search topics…"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              className="pl-8 pr-3 py-2 text-xs focus:outline-none w-48 rounded-xl surface-input"
              style={{ color: "var(--text)" }}
            />
          </div>
          <select
            value={filterCat}
            onChange={(e) => setFilterCat(e.target.value)}
            className="px-3 py-2 text-xs focus:outline-none rounded-xl surface-input"
            style={{ color: "var(--text-dim)" }}
          >
            <option value="all">All categories</option>
            {uniqueCats.map((c) => <option key={c} value={c}>{c}</option>)}
          </select>
        </div>
      </motion.div>

      {/* Graph container */}
      <div className="flex-1 w-full h-full relative">
        {sessions.length === 0 ? (
          <div className="relative w-full h-full flex flex-col items-center justify-center overflow-hidden">
            {/* Ghost background representation of nodes and edges */}
            <div className="absolute inset-0 opacity-10 pointer-events-none filter blur-[2px] flex items-center justify-center">
              <div className="w-[500px] h-[500px] border border-dashed rounded-full flex items-center justify-center relative">
                <div className="absolute w-[300px] h-[300px] border border-dashed rounded-full" />
                <div className="absolute top-10 left-1/3 w-6 h-6 rounded-full" style={{ background: "var(--olive)" }} />
                <div className="absolute top-1/2 right-10 w-8 h-8 rounded-full" style={{ background: "var(--olive)" }} />
                <div className="absolute bottom-12 left-1/4 w-10 h-10 rounded-full" style={{ background: "var(--olive)" }} />
              </div>
            </div>
            
            <div className="relative z-10 flex flex-col items-center gap-4 text-center max-w-xs px-6">
              <div className="text-5xl">🌌</div>
              <div className="text-lg font-space font-bold" style={{ color: "var(--text)" }}>Your constellation awaits</div>
              <p style={{ color: "var(--text-dim)" }} className="text-xs">
                Complete your first learning challenge, and your topic nodes will begin to map out and grow here.
              </p>
            </div>
          </div>
        ) : (
          <ReactFlow
            nodes={nodes}
            edges={edges}
            onNodesChange={onNodesChange}
            onEdgesChange={onEdgesChange}
            nodeTypes={nodeTypes}
            fitView
            fitViewOptions={{ padding: 0.25 }}
            minZoom={0.25}
            maxZoom={1.5}
          >
            <Background color="var(--olive-dim)" gap={20} size={1} />
            <Controls />
            <MiniMap
              nodeColor={(n) => CATEGORY_COLORS[n.data?.session?.category] ?? "var(--olive)"}
              maskColor="rgba(244,239,230,0.8)"
              style={{ background: "var(--bg-card)", border: "1px solid var(--border-dim)" }}
            />
          </ReactFlow>
        )}

        {/* Slide-out detail panel */}
        <AnimatePresence>
          {activeDetailSession && (
            <NodeDetail
              session={activeDetailSession}
              onClose={() => setSelectedSession(null)}
            />
          )}
        </AnimatePresence>
      </div>
    </motion.div>
  );
}
